---
- name: Install dotfiles
  hosts: localhost
  become: true
  when: (ansible_system == "Linux") or (ansible_distribution == "MacOSX")

  tasks:
    - name: Check if dotfiles exists
      stat:
        path: "{{ dotfiles_path }}"
      register: dotfiles_dir

    - name: Clone dotfiles
      git:
        repo: "git@github.com:KirkEasterson/.dotfiles.git"
        dest: "{{ dotfiles_path }}"
        key_file: "{{ sshkey_github_path }}"
        accept_hostkey: true
        track_submodules: true
        recursive: true
      when: dotfiles_dir.stat.exists == false

      # TODO: extend this for other package managers
    - name: Install stow
      become: true
      pacman:
        state: present
        name: stow

    - name: Install dotfiles
      shell:
        cmd: "{{ dotfiles_path }}/install.sh"
      when: dotfiles_dir.stat.exists == false
