- name: Install python3 and pip3
  become: true
  apt:
    install_recommends: no
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv

- name: Install pip3 packages
  become: true
  pip:
    executable: pip3
    extra_args: '--quiet'
    name:
      - autopep8
      - black
      - ipython
      - matplotlib
      - neovim-remote
      - numpy
      - pandas
      - pexpect
      - ptpython
      - pylint
      - pyright
      # - pytorch
      - scikit-learn
      - scipy
      - tensorflow
      - ueberzug
