- name: Install nodejs and npm
  become: true
  apt:
    install_recommends: no
    name:
      - npm
      - nodejs

# - name: Install npm packages
#   become: true
#   pip:
#     name:
#       - ts-server
