---
- name: "Install bluetooth tools"
  become: true
  vars:
    bluezutils:
      Archlinux: "bluez-utils"
      Debian: "bluez-tools"
      Suse: "bluez-firmware"
    hidapi:
      Archlinux: "hidapi"
      Debian: "libhidapi-libusb0"
      Suse: "libhidapi-libusb0"
    sbc:
      Archlinux: "sbc"
      Debian: "libsbc1"
      Suse: "sbc"
  ansible.builtin.package:
    name:
      - "blueman"
      - "bluez"
      - "{{ bluezutils[ansible_facts['os_family']] }}"
      - "{{ hidapi[ansible_facts['os_family']] }}"
      - "{{ sbc[ansible_facts['os_family']] }}"

- name: "Enable bluetooth"
  become: true
  ansible.builtin.systemd:
    name: "bluetooth"
    enabled: true
