---
- name: Install bluetooth tools
  become: true
  vars:
    bluezutils:
      Archlinux: "bluez-utils"
      Debian: "bluez-tools"
    hidapi:
      Archlinux: "hidapi"
      Debian: "libhidapi-libusb0"
    sbc:
      Archlinux: "sbc"
      Debian: "libsbc1"
  ansible.builtin.package:
    name:
      - "blueman"
      - "bluez"
      - "{{ bluezutils[ansible_facts['os_family']] }}"
      - "{{ hidapi[ansible_facts['os_family']] }}"
      - "{{ sbc[ansible_facts['os_family']] }}"
