---
- name: Install bluetooth from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - blueman
      - bluez
      - bluez-utils
      - hidapi
      - sbc
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install bluetooth from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - cbatticon
      - volumeicon-alsa
  when: ansible_facts['os_family'] == "Debian"
