---
- name: "Install communication tools"
  become: true
  vars:
    element:
      Archlinux: "element-desktop"
      Darwin: "element"
    signal:
      Archlinux: "signal-desktop"
      Darwin: "signal"
    telegram:
      Archlinux: "telegram-desktop"
      Darwin: "telegram"
  ansible.builtin.package:
    name:
      - "discord"
      - "{{ element[ansible_facts['os_family']] }}"
      - "{{ signal[ansible_facts['os_family']] }}"
      - "{{ telegram[ansible_facts['os_family']] }}"

- name: "Install communication tools from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "slack-desktop"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install communication tools from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "homebrew/cask/slack"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Install email clients"
  become: true
  ansible.builtin.package:
    name:
      - "neomutt"
      - "thunderbird"

- name: "Install email clients from pacman"
  become: true
  community.general.pacman:
    state: "present"
    name:
      - "systray-x-common"
  when: "ansible_facts['os_family'] == 'Archlinux'"
