---
- name: "Install docker"
  become: true
  ansible.builtin.package:
    name:
      - "docker"
      - "docker-buildx"
      - "docker-compose"
      # - "lazydocker" # only in AUR

- name: "Add current user to the docker group"
  become: true
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    groups: "docker"
    append: true

- name: "Enable docker service"
  become: true
  ansible.builtin.systemd:
    name: "docker"
    enabled: true
