---
- name: "Install image editors"
  become: true
  ansible.builtin.package:
    name:
      - "gimp"

- name: "Install video editors"
  become: true
  ansible.builtin.package:
    name:
      - "kdenlive"

- name: "Install audio editors"
  become: true
  ansible.builtin.package:
    name:
      # - "ardour" # not on brew
      - "audacity"
      # - "reaper" # not on zypper

- name: "Add vscode repository for suse"
  become: true
  community.general.zypper_repository:
    repo: "obs://devel:tools:ide:vscode devel_tools_ide_vscode"
    state: "present"
    runrefresh: true
  when: "ansible_facts['os_family'] == 'Suse'"

# TODO:
# - install vscodium repository
#     https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
# - install intellij repository
#     https://www.linuxcapable.com/how-to-install-intellij-idea-on-ubuntu-linux/
- name: "Install code editors"
  become: true
  vars:
    vscode:
      Archlinux: "code"
      Debian: "code"
      Darwin: "visual-studio-code"
      Suse: "code"
    intellij:
      Archlinux: "intellij-idea-community-edition"
      Debian: "intellij-idea-community"
      Darwin: "intellij"
  ansible.builtin.package:
    name:
      - "emacs"
      - "neovide" # not in apt
      - "neovim"
      - "vim"
      - "{{ vscode[ansible_facts['os_family']] }}"
      - "{{ intellij[ansible_facts['os_family']] }}"

- name: "Install text editors"
  become: true
  ansible.builtin.package:
    name:
      - "libreoffice"

- name: "Install document build tools"
  become: true
  ansible.builtin.package:
    name:
      - "pandoc"

- name: "Install document build tools from pacman"
  become: true
  community.general.pacman:
    state: "present"
    name:
      - "biber"
      - "texlive-latex"
      - "texlive-latexextra"
      - "texlive-latexrecommended"
      - "texlive-luatex"
      - "texlive-mathscience"
      - "texlive-music"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install document build tools from apt"
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "texlive-base"
      - "texlive-bibtex-extra"
      - "texlive-extra-utils"
      - "texlive-font-utils"
      - "texlive-fonts-extra"
      - "texlive-fonts-recommended"
      - "texlive-lang-european"
      - "texlive-latex-base"
      - "texlive-latex-extra"
      - "texlive-latex-recommended"
      - "texlive-luatex"
      - "texlive-music"
      - "texlive-science"
  when: "ansible_facts['os_family'] == 'Debian'"

- name: "Install document build tools from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "texlive"
  when: "ansible_facts['os_family'] == 'Darwin'"
