---
- name: Install image editors from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - gimp
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install image editors from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - gimp
  when: ansible_facts['os_family'] == "Debian"

- name: Install image editors from homebrew
  community.general.homebrew:
    state: present
    name:
      - homebrew/cask/gimp
  when: ansible_facts['os_family'] == "Darwin"

- name: Install video editors from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - kdenlive
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install video editors from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - kdenlive
  when: ansible_facts['os_family'] == "Debian"

- name: Install video editors from homebrew
  community.general.homebrew:
    state: present
    name:
      - homebrew/cask/kdenlive
  when: ansible_facts['os_family'] == "Darwin"

- name: Install audio editors from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - ardour
      - audacity
      - reaper
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install audio editors from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - ardour
      # - audacity
      # - reaper
  when: ansible_facts['os_family'] == "Debian"

- name: Install audio editors from homebrew
  community.general.homebrew:
    state: present
    name:
      # - homebrew/cask/ardour
      - homebrew/cask/audacity
      - homebrew/cask/reaper
  when: ansible_facts['os_family'] == "Darwin"

- name: Install code editors from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - "code"
      - "emacs"
      - "helix"
      - "neovide"
      - "neovim"
      - "python-pynvim"
      - "vim"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install code editors from AUR
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - "intellij-idea-community-edition"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install code editors from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      # - "code" # TODO: install PPA for this
      - "emacs"
      - "helix"
      - "neovide"
      - "neovim"
      - "python3-neovim"
      - "vim"
  when: ansible_facts['os_family'] == "Debian"

- name: Install code editors from homebrew
  community.general.homebrew:
    state: present
    name:
      - "emacs"
      - "helix"
      - "homebrew/cask/visual-studio-code"
      - "neovide"
      - "neovim"
      - "vim"
  when: ansible_facts['os_family'] == "Darwin"

# # TODO: make this work on arch
# - name: Install code editor tools from pip
#   become: true
#   become_user: "{{ remote_regular_user }}"
#   ansible.builtin.pip:
#     name:
#       - "neovim"

# # TODO: make this work on arch
# - name: Install neovim package globally.
#   become: true
#   become_user: "{{ remote_regular_user }}"
#   community.general.npm:
#     name: "neovim"
#     global: true

# # TODO: make this work on arch
# - name: Install neovim-client package globally.
#   become: true
#   become_user: "{{ remote_regular_user }}"
#   community.general.npm:
#     name: "neovim-client"
#     global: true

- name: Install text editors from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - "libreoffice"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install text editors from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "libreoffice"
  when: ansible_facts['os_family'] == "Debian"

- name: Install text editors from homebrew
  community.general.homebrew:
    state: present
    name:
      - "homebrew/cask/libreoffice"
  when: ansible_facts['os_family'] == "Darwin"

- name: Install document build tools from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - "biber"
      - "texlive-latex"
      - "texlive-latexextra"
      - "texlive-latexrecommended"
      - "texlive-luatex"
      - "texlive-mathscience"
      - "texlive-music"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install document build tools from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "texlive-base"
      - "texlive-bibtex-extra"
      - "texlive-extra-utils"
      - "texlive-font-utils"
      - "texlive-fonts-extra"
      - "texlive-fonts-recommended"
      - "texlive-lang-european"
      - "texlive-latex-base"
      - "texlive-latex-extra"
      - "texlive-latex-recommended"
      - "texlive-luatex"
      - "texlive-music"
      - "texlive-science"
  when: ansible_facts['os_family'] == "Debian"

- name: Install document build tools from homebrew
  community.general.homebrew:
    state: present
    name:
      - "texlive"
  when: ansible_facts['os_family'] == "Darwin"

- name: Install pandoc from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - "pandoc"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install pandoc from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "pandoc"
  when: ansible_facts['os_family'] == "Debian"

- name: Install pandoc from homebrew
  community.general.homebrew:
    state: present
    name:
      - "pandoc"
  when: ansible_facts['os_family'] == "Darwin"
