---
- name: "Install file managers"
  become: true
  vars:
    pcmanfm:
      Archlinux: "pcmanfm-gtk3"
      Debian: "pcmanfm"
  ansible.builtin.package:
    name:
      - "gvfs"
      - "gvfs-google"
      - "gvfs-mtp"
      - "gvfs-nfs"
      - "gvfs-smb"
      - "gvfs-wsdd"
      - "nfs-utils"
      - "udiskie"
      - "{{ pcmanfm[ansible_facts['os_family']] }}"
  when: "ansible_system == 'Linux'"

- name: "Install TUI file managers"
  become: true
  ansible.builtin.package:
    name:
      - "ranger"
      - "yazi"

- name: "Install TUI file manager tools"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "dragon-drop"
  when: "ansible_facts['os_family'] == 'Archlinux'"
