---
- name: "Install file managers"
  become: true
  vars:
    pcmanfm:
      Archlinux: "pcmanfm-gtk3"
      Debian: "pcmanfm"
  ansible.builtin.package:
    name:
      - "udiskie"
      - "gvfs"
      - "gvfs-mtp"
      - "{{ pcmanfm[ansible_facts['os_family']] }}"
  when: "ansible_system == 'Linux'"

- name: "Install ranger"
  become: true
  ansible.builtin.package:
    name:
      - "ranger"
