---
- name: Install game clients from pacman
  become: true
  pacman:
    state: present
    name:
      - lutris
      - steam
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install game clients from AUR
  become: true
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - minecraft-launcher
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install game clients from apt
  become: true
  apt:
    install_recommends: no
    name:
      - lutris
      - steam
  when: ansible_facts['os_family'] == "Debian"

- name: Install game clients from homebrew
  homebrew:
    state: present
    name:
      - homebrew/cask/minecraft
      - homebrew/cask/steam
  when: ansible_facts['os_family'] == "Darwin"
