---
- name: "Install game clients"
  become: true
  ansible.builtin.package:
    name:
      - "lutris"
      - "minetest"
      - "minetest-common"
      - "minetest-server"
      - "steam"
      - "wine"
      - "wine-mono"
      - "winetricks"
  when: "ansible_system == 'Linux'"

- name: "Install game clients from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "atlauncher-bin"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install game clients from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "homebrew/cask/atlauncher"
      - "homebrew/cask/minecraft"
      - "homebrew/cask/steam"
      - "minetest"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Install video drivers"
  become: true
  ansible.builtin.package:
    name:
      - "lib32-vulkan-nouveau"
      - "vulkan-nouveau"
      - "xf86-video-nouveau"
  when: "ansible_system == 'Linux'"
