---
- name: "Install game clients from pacman"
  become: true
  ansible.builtin.package:
    name:
      - "lutris"
      - "steam"
  when: "ansible_system == 'Linux'"

- name: "Install game clients from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "atlauncher-bin"
      - "minecraft-launcher"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install game clients from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "homebrew/cask/atlauncher"
      - "homebrew/cask/minecraft"
      - "homebrew/cask/steam"
  when: "ansible_facts['os_family'] == 'Darwin'"
