---
- name: "Install key mappers"
  become: true
  vars:
    xmodmap:
      Archlinux: "sxhkd"
      Debian: "x11-xserver-utils" # contains xmodmap
  ansible.builtin.package:
    name:
      - "wtype"
      - "kmonad"
      - "xdotool"
      - "{{ xmodmap[ansible_facts['os_family']] }}"
  when: "ansible_system == 'Linux'"

- name: "Install key mappers from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "koekeishiya/formulae/skhd"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Start skhd service"
  ansible.builtin.command:
    cmd: "skhd --start-service"
  changed_when: false
  when: "ansible_facts['os_family'] == 'Darwin'"
