---
- name: Install launchers from pacman
  become: true
  pacman:
    state: present
    name:
      - rofi
      - wofi
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install launchers from apt
  become: true
  apt:
    install_recommends: no
    name:
      - rofi
      - wofi
  when: ansible_facts['os_family'] == "Debian"

# # TODO: find a better macos launcher
# - name: Install launchers from homebrew
#   homebrew:
#     state: present
#     name:
#       - rofi
#       - wofi
#   when: ansible_facts['os_family'] == "Darwin"
