---
- name: Install launchers from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - rofi
      - wofi
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install launchers from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - rofi
      - wofi
  when: ansible_facts['os_family'] == "Debian"

# # TODO: find a better macos launcher
# - name: Install launchers from homebrew
#   community.general.homebrew:
#     state: present
#     name:
#       - rofi
#       - wofi
#   when: ansible_facts['os_family'] == "Darwin"
