---
# TODO: brightnessctl, volume key stuff, etc
- import_tasks:
    file: bluetooth.yml
- import_tasks:
    file: browsers.yml
- import_tasks:
    file: communication.yml
- import_tasks:
    file: dev.yml
- import_tasks:
    file: editors.yml
- import_tasks:
    file: file_managers.yml
- import_tasks:
    file: games.yml
- import_tasks:
    file: key_mappers.yml
- import_tasks:
    file: launchers.yml
- import_tasks:
    file: media.yml
- import_tasks:
    file: notifications.yml
- import_tasks:
    file: screenshot.yml
- import_tasks:
    file: systray.yml
- import_tasks:
    file: terminal.yml
- import_tasks:
    file: utilities.yml
- import_tasks:
    file: window_managers.yml
