---
- name: Install pdf viewers from pacman
  become: true
  pacman:
    state: present
    name:
      - evince
      - pdfarranger
      - xournalpp
      - zathura
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install pdf viewers from apt
  become: true
  apt:
    install_recommends: no
    name:
      - evince
      - pdfarranger
      - xournalpp
      - zathura
  when: ansible_facts['os_family'] == "Debian"

- name: Install pdf viewers from homebrew
  homebrew:
    state: present
    name:
      - evince
      - homebrew/cask/xournal-plus-plus
  when: ansible_facts['os_family'] == "Darwin"

- name: Install image viewers from pacman
  become: true
  pacman:
    state: present
    name:
      - nsxiv
      - feh
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install image viewers from apt
  become: true
  apt:
    install_recommends: no
    name:
      - nsxiv
      - feh
  when: ansible_facts['os_family'] == "Debian"

  # - name: Install image viewers from homebrew
  #   homebrew:
  #     state: present
  #     name:
  #       - nsxiv
  #       - feh
  #   when: ansible_facts['os_family'] == "Darwin"

- name: Install video viewers from pacman
  become: true
  pacman:
    state: present
    name:
      - mpv
      - vlc
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install video viewers from apt
  become: true
  apt:
    install_recommends: no
    name:
      - mpv
      - vlc
  when: ansible_facts['os_family'] == "Debian"

- name: Install video viewers from homebrew
  homebrew:
    state: present
    name:
      - homebrew/cask/vlc
      - mpv
  when: ansible_facts['os_family'] == "Darwin"

- name: Install music players from pacman
  become: true
  pacman:
    state: present
    name:
      - rhythmbox
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install music players from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - spotify-adblock
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install music players from apt
  become: true
  apt:
    install_recommends: no
    name:
      - rhythmbox
      # - spotify-adblock
  when: ansible_facts['os_family'] == "Debian"

# # TODO: find music players for mac
# - name: Install music players from homebrew
#   homebrew:
#     state: present
#     name:
#       - rhythmbox
#   when: ansible_facts['os_family'] == "Darwin"
