---
- name: "Install pdf viewers"
  become: true
  ansible.builtin.package:
    name:
      - "zathura"
      - "zathura-pdf-mupdf"
  when: "ansible_system == 'Linux'"

- name: "Install pdf viewers from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "evince"
      - "homebrew/cask/xournal-plus-plus"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Install image viewers"
  become: true
  ansible.builtin.package:
    name:
      - "feh"
      - "nsxiv"
      - "openslide"
  when: "ansible_system == 'Linux'"

- name: "Install image viewers from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "ueberzugpp"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install video players"
  become: true
  ansible.builtin.package:
    name:
      - "mpv"
      - "vlc"

# TODO: find music players for mac
- name: "Install music players"
  become: true
  ansible.builtin.package:
    name:
      - "playerctl"
  when: "ansible_system == 'Linux'"

- name: "Install spotify from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "spotify-adblock"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install spotify from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "spotify"
  when: "ansible_facts['os_family'] == 'Darwin'"
