---
- name: Install notification services from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - dunst
      - mako
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install notification services from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - dunst
      - mako
  when: ansible_facts['os_family'] == "Debian"
