---
- name: Install screenshot utilities from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - flameshot
      - grim
      - slurp
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install screenshot utilities from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - flameshot
      - grim
      - slurp
  when: ansible_facts['os_family'] == "Debian"

- name: Install screenshot utilities from homebrew
  community.general.homebrew:
    state: present
    name:
      - homebrew/cask/flameshot
  when: ansible_facts['os_family'] == "Darwin"
