---
- name: Install systray tools from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - cbatticon
      - volumeicon
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install systray tools from apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - cbatticon
      - volumeicon-alsa
  when: ansible_facts['os_family'] == "Debian"
