---
- name: Install systray tools
  become: true
  vars:
    volumeicon:
      Archlinux: "volumeicon"
      Debian: "volumeicon-alsa"
  ansible.builtin.package:
    name:
      - "{{ volumeicon[ansible_facts['os_family']] }}"
  when: ansible_system == "Linux"
