---
- name: "Install terminal emulators"
  become: true
  ansible.builtin.package:
    name:
      - "alacritty"
      - "kitty"
      - "wezterm"
      - "xterm"

#   # TODO: find a ppa for ubuntu
- name: "Install shell prompt"
  become: true
  ansible.builtin.package:
    name:
      - "starship" # not in apt

- name: "Install CLI tools"
  become: true
  ansible.builtin.package:
    name:
      - "asciiquarium"
      - "bat"
      - "bc" # needed for some scripts
      - "btop"
      - "catimg"
      - "cmatrix"
      - "curl"
      - "direnv"
      - "dust"
      - "eza"
      - "fd"
      - "figlet"
      - "fzf"
      - "htop"
      - "hyperfine"
      - "less"
      - "neofetch"
      - "procs"
      - "ripgrep"
      - "sd"
      - "tmux"
      - "tmuxp"
      - "tree"
