---
- name: "Install terminal emulators"
  become: true
  ansible.builtin.package:
    name:
      - "alacritty"
      - "kitty"
      - "wezterm"
      - "xterm"

#   # TODO: find a ppa for ubuntu
- name: "Install shell prompt"
  become: true
  ansible.builtin.package:
    name:
      - "starship" # not in apt

- name: "Install CLI tools"
  become: true
  vars:
    bat:
      Archlinux: "bat"
      Debian: "batcat"
      Suse: "bat"
      Darwin: "bat"
  ansible.builtin.package:
    name:
      - "asciiquarium"
      - "bc" # needed for some scripts
      - "btop"
      - "catimg"
      - "cmatrix"
      - "curl"
      - "direnv"
      - "dust"
      - "eza"
      - "fd"
      - "figlet"
      - "fzf"
      - "htop"
      - "hyperfine"
      - "less"
      - "lshw"
      - "man"
      - "neofetch"
      - "nmap"
      - "procs"
      - "ripgrep"
      - "sd"
      - "smartmontools"
      - "tmux"
      - "tmuxp"
      - "tree"
      - "wget"
      - "{{ bat[ansible_facts['os_family']] }}"

- name: "Create symlink for bat"
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "/usr/bin/bat"
    state: "link"
    force: false
  when: "ansible_facts['os_family'] == 'Debian'"
