---
- name: "Install vpn from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "nordvpn-bin"
      - "nordtray-bin"
  when: "ansible_facts['os_family'] == 'Archlinux'"

# - name: "Install vpn from apt"
#   become: true
#   ansible.builtin.apt:
#     install_recommends: false
#     name:
#       - "nordvpn"
#   when: "ansible_facts['os_family'] == 'Debian'"

- name: "Install vpn from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "homebrew/cask/nordvpn"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Add current user to the nordvpn group"
  become: true
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    groups: "nordvpn"
    append: true

- name: "Enable nordvpnd service"
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.systemd_service:
    state: "started"
    name: "nordvpnd"
    enabled: true

  # TODO: login in with key from vault
- name: "Install password manager from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "1password"
      - "1password-cli"
  when: "ansible_facts['os_family'] == 'Archlinux'"

# - name: "Install password manager from apt"
#   become: true
#   ansible.builtin.apt:
#     install_recommends: false
#     name:
#       - "1password"
#   when: "ansible_facts['os_family'] == 'Debian'"

- name: "Install password manager from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "homebrew/cask/1password"
      - "homebrew/cask/1password-cli"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Install systray tools"
  become: true
  vars:
    volumeicon:
      Archlinux: "volumeicon"
      Debian: "volumeicon-alsa"
  ansible.builtin.package:
    name:
      - "{{ volumeicon[ansible_facts['os_family']] }}"
  when: "ansible_system == 'Linux'"

- name: "Clipboard mangers"
  become: true
  ansible.builtin.package:
    name:
      - "wl-clipboard"
      - "xcopy"
  when: "ansible_system == 'Linux'"
