---
- name: Install vpn from AUR
  become: true
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - nordvpn-bin
      - nordtray-bin
  when: ansible_facts['os_family'] == "Archlinux"

# - name: Install vpn from apt
#   become: true
#   apt:
#     install_recommends: no
#     name:
#       - nordvpn
#   when: ansible_facts['os_family'] == "Debian"

- name: Install vpn from homebrew
  homebrew:
    state: present
    name:
      - homebrew/cask/nordvpn
  when: ansible_facts['os_family'] == "Darwin"

- name: Install password manager from AUR
  become: true
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - 1password
      - 1password-cli
  when: ansible_facts['os_family'] == "Archlinux"

# - name: Install password manager from apt
#   become: true
#   apt:
#     install_recommends: no
#     name:
#       - 1password
#   when: ansible_facts['os_family'] == "Debian"

- name: Install password manager from homebrew
  homebrew:
    state: present
    name:
      - homebrew/cask/1password
      - homebrew/cask/1password-cli
  when: ansible_facts['os_family'] == "Darwin"

- name: Install multi-monitor tools from AUR
  become: true
  pacman:
    state: present
    name:
      - arandr
      - autorandr
      - xrandr
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install multi-monitor tools from apt
  become: true
  apt:
    install_recommends: no
    name:
      - arandr
      - autorandr
      - xrandr
  when: ansible_facts['os_family'] == "Debian"

# - name: Install multi-monitor tools from homebrew
#   homebrew:
#     state: present
#     name:
#       - arandr
#       - autorandr
#       - xrandr
#   when: ansible_facts['os_family'] == "Darwin"
