---
- name: "Install i3"
  become: true
  ansible.builtin.package:
    name:
      - "i3-wm"
      - "polybar"
  when: "ansible_system == 'Linux'"

- name: "Install awesome"
  become: true
  ansible.builtin.package:
    name:
      - "awesome"
      - "luarocks"
      - "sound-theme-freedesktop"
  when: "ansible_system == 'Linux'"

- name: "Install awesomewm tools from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "awesome-freedesktop-git"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install awesomewm tools from apt"
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "awesome-extra"
  when: "ansible_facts['os_family'] == 'Debian'"

- name: "Install sway"
  become: true
  vars:
    sway:
      Archlinux: "sway"
      Debian: "sway"
      Darwin: "sway"
      Suse: "sway-branding-upstream"
  ansible.builtin.package:
    name:
      - "kanshi"
      - "swaybg"
      - "swayidle"
      - "swaylock"
      - "waybar"
      - "wf-recorder"
      - "wlr-randr"
      - "xdg-desktop-portal-gnome"
      - "xdg-desktop-portal-gtk"
      - "xdg-desktop-portal-kde"
      - "xdg-desktop-portal-wlr"
      - "xdg-desktop-portal-xapp"
      - "{{ sway[ansible_facts['os_family']] }}"
  when: "ansible_system == 'Linux'"

- name: "Install sway tools from AUR"
  become: true
  become_user: "{{ remote_regular_user }}"
  kewlfft.aur.aur:
    state: "present"
    use: "yay"
    name:
      - "wlopm"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install river"
  become: true
  ansible.builtin.package:
    name:
      - "river"
  when: "ansible_system == 'Linux'"

- name: "Install hyprland"
  become: true
  ansible.builtin.package:
    name:
      - "hyprcursor"
      - "hyprgraphics"
      - "hypridle"
      - "hyprland"
      - "hyprland-protocols"
      - "hyprland-qt-support"
      - "hyprland-qtutils"
      - "hyprlock"
      - "hyprpaper"
      - "hyprpolkitagent"
      - "hyprutils"
      - "xdg-desktop-portal-hyprland"
  when: "ansible_system == 'Linux'"

- name: "Install yabai from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "koekeishiya/formulae/yabai"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Start yabai service"
  ansible.builtin.command:
    cmd: "yabai --start-service"
  changed_when: false
  when: "ansible_facts['os_family'] == 'Darwin'"
