---
# https://macos-defaults.com/desktop/
- name: "Set desktop settings"
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # disable desktop icons
    - key: "CreateDesktop"
      type: "bool"
      value: false

    # disable external disk icons
    - key: "ShowExternalHardDrivesOnDesktop"
      type: "bool"
      value: false

    # disable removable media icons
    - key: "ShowRemovableMediaOnDesktop"
      type: "bool"
      value: false
  notify: "Restart Finder"
