---
# https://macos-defaults.com/dock/

- name: "Set desktop settings"
  community.general.osx_defaults:
    domain: "com.apple.dock"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # set dock to autohide
    - key: "autohide"
      type: "bool"
      value: true

    # set dock animation time to 0
    - key: "autohide-time-modifier"
      type: "float"
      value: 0

    # set dock autohide delay to 0
    - key: "autohide-delay"
      type: "float"
      value: 0

    # set dock to left side
    - key: "orientation"
      type: "string"
      value: "left"

    # remove recents from dock
    - key: "show-recents"
      type: "bool"
      value: false

    # set dock animation to suck
    - key: "mineffect"
      type: "string"
      value: "suck"

    # don't show only active applications
    - key: "static-only"
      type: "bool"
      value: false

    # disable scroll to expose app
    - key: "scroll-to-open"
      type: "bool"
      value: false
  register: "dock_settings"

- name: "Restart dock"
  ansible.builtin.command: "killall Dock"
  changed_when: false
  when: "dock_settings.changed"
