---
# https://macos-defaults.com/feedback-assistant/
- name: Set macos feedback assistant settings
  hosts: localhost
  become: true
  when: ansible_distribution == "MacOSX"

  tasks:

    # defaults write com.apple.appleseed.FeedbackAssistant "Autogather" -bool "false"
    - name: Don't autogather large files for feedback reports
      community.general.osx_defaults:
        domain: com.apple.appleseed.FeedbackAssistant
        key: Autogather
        type: bool
        value: false
        state: present
