---
# https://macos-defaults.com/finder/

- name: "Set finder settings"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # show file extensions
    - {
        domain: "com.apple.finder",
        key: "ShowPathBar",
        type: "bool",
        value: true,
      }

    # show path bar
    - {
        domain: "NSGlobalDomain",
        key: "AppleShowAllExtensions",
        type: "bool",
        value: true,
      }

    # set column view
    - {
        domain: "com.apple.finder",
        key: "FXPreferredViewStyle",
        type: "string",
        value: "clmv",
      }

    # keep folders on top
    - {
        domain: "com.apple.finder",
        key: "FXSortFoldersFirst",
        type: "bool",
        value: true,
      }

    # disable file extension change warning
    - {
        domain: "com.apple.finder",
        key: "FXEnableExtensionChangeWarning",
        type: "bool",
        value: false,
      }

    # save to disk instead of icloud
    - {
        domain: "NSGlobalDomain",
        key: "NSDocumentSaveNewDocumentsToCloud",
        type: "bool",
        value: false,
      }

    # disable toolbar title delay
    - {
        domain: "NSGlobalDomain",
        key: "NSToolbarTitleViewRolloverDelay",
        type: "float",
        value: 0,
      }

    # set sidebar icon size
    - {
        domain: "NSGlobalDomain",
        key: "NSTableViewDefaultSizeMode",
        type: "int",
        value: 1,
      }
  register: "finder_settings"

- name: "Restart Finder"
  ansible.builtin.command: "killall Finder"
  changed_when: false
  when: "finder_settings.changed"
