---
# https://macos-defaults.com/menubar/

- name: "Set menu-bar settings"
  community.general.osx_defaults:
    domain: "com.apple.menuextra.clock"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # - enable flash date separators
    - key: "FlashDateSeparators"
      type: "bool"
      value: true

    # change date format
    - key: "DateFormat"
      type: "string"
      value: "\"EEE MMM d HH:mm:ss\""
  register: "menubar_settings"

- name: "Restart SystemUIServer"
  ansible.builtin.command: "killall SystemUIServer"
  changed_when: false
  when: "menubar_settings.changed"
