---
# https://macos-defaults.com/mission-control/

- name: "Set mission-control dock settings"
  community.general.osx_defaults:
    domain: "com.apple.dock"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # disable re-arranging workspaces by most recent use
    - key: "mru-spaces"
      type: "bool"
      value: false
  notify: "Restart Finder"

- name: "Set mission-control space settings"
  community.general.osx_defaults:
    domain: "com.apple.spaces"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # enable separate spaces for displays
    - key: "spans-displays"
      type: "bool"
      value: true
  notify: "Restart SystemUIServer"
