---
# https://macos-defaults.com/safari/

- name: "Show full url"
  community.general.osx_defaults:
    domain: "com.apple.Safari"
    key: "ShowFullURLInSmartSearchField"
    type: "bool"
    value: true
    state: "present"
  notify: "Restart Safari"
