---
# https://macos-defaults.com/safari/

# defaults write com.apple.Safari "ShowFullURLInSmartSearchField" -bool "true" && killall Safari
- name: "Show full url"
  community.general.osx_defaults:
    domain: "com.apple.Safari"
    key: "ShowFullURLInSmartSearchField"
    type: "bool"
    value: true
    state: "present"

# NOTE: always do this last
- name: "Restart Safari"
  ansible.builtin.command: "killall Safari"
  changed_when: false
