---
# https://macos-defaults.com/screenshots/

- name: "Set screenshot settings"
  community.general.osx_defaults:
    domain: "com.apple.screencapture"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "present"
  loop:
    # disable shadow
    - { key: "disable-shadow", type: "bool", value: true }

    # include date in filename
    - { key: "include-date", type: "bool", value: true }

    # change screenshot save location
    - { key: "location", type: "string", value: "{{ screenshots_path }}" }

    # disable screenshot thumbnail
    - { key: "show-thumbnail", type: "bool", value: "false" }

    # set screenshot file type to png
    - { key: "type", type: "string", value: "png" }
  register: "screenshot_settings"

- name: "Restart system UI"
  ansible.builtin.command: "killall SystemUIServer"
  changed_when: false
  when: "screenshot_settings.changed"
