---
# https://macos-defaults.com/trackpad/

# defaults write com.apple.AppleMultitouchTrackpad "Dragging" -bool "true"
- name: "Enable dragging without drag lock"
  community.general.osx_defaults:
    domain: "com.apple.AppleMultitouchTrackpad"
    key: "Dragging"
    type: "bool"
    value: true
    state: "present"
