---
- name: "Check if dotfiles exists"
  ansible.builtin.stat:
    path: "{{ dotfiles_path }}"
  register: "dotfiles_dir"

- name: "Clone dotfiles" # noqa: latest[git]
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.git:
    repo: "git@github.com:KirkEasterson/.dotfiles.git"
    dest: "{{ dotfiles_path }}"
    key_file: "{{ github_key_path }}"
    accept_hostkey: true
    recursive: true
    depth: 1
  when: "not dotfiles_dir.stat.exists"
  changed_when: false

- name: "Install stow"
  become: true
  ansible.builtin.package:
    name:
      - "stow"

- name: "Install dotfiles"
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.command:
    cmd: "{{ dotfiles_path }}/install.sh"
  when: "not dotfiles_dir.stat.exists"
  changed_when: false
