---
- name: "Check if firefox repo exists"
  ansible.builtin.stat:
    path: "{{ firefox_path }}"
  register: "firefox_dir"

- name: "Clone firefox-profile" # noqa: latest[git]
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.git:
    repo: "git@github.com:KirkEasterson/firefox-profile.git"
    dest: "{{ firefox_path }}"
    key_file: "{{ github_key_path }}"
    accept_hostkey: true
    recursive: true
    update: true
  when: "not dotfiles_dir.stat.exists"
  changed_when: false

- name: "Install stow"
  become: true
  ansible.builtin.package:
    name:
      - "stow"

- name: "Install firefox-profile"
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.command:
    cmd: "{{ firefox_path }}/install.sh"
  when: "not firefox_dir.stat.exists"
  changed_when: false
