---
- name: Check if scripts exists
  ansible.builtin.stat:
    path: "{{ scripts_path }}"
  register: scripts_dir

- name: Clone scripts # noqa: latest[git]
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.git:
    repo: "git@github.com:KirkEasterson/scripts.git"
    dest: "{{ scripts_path }}"
    key_file: "{{ github_key_path }}"
    depth: 1
  when: not scripts_dir.stat.exists
  changed_when: false
