---
- hosts: localhost
  connection: local

  pre_tasks:
    - include: roles/common/tasks/update_repos/pacman.yml

  tasks:
    - include: roles/arch/local.yml

  post_tasks:
    - include: roles/common/tasks/update_repos/pacman.yml
