- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
        upgrade: yes
      changed_when: false
    - include: tasks/purge_snapd.yml

  tasks:
    - include: tasks/directories.yml
    - include: tasks/git_repos.yml
    - include: tasks/locale.yml
    - include: tasks/groups.yml
    - include: tasks/font_install.yml
    - include: tasks/programs/local.yml
    - include: tasks/greeter.yml
    - include: tasks/plymouth.yml
    - include: tasks/pipewire.yml
    - include: tasks/networking.yml

  post_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
        upgrade: yes
      changed_when: false
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
