- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
      changed_when: false
    - include: tasks/purge_snapd.yml

  tasks:
    - include: tasks/locale.yml
    - include: tasks/directories.yml
    - include: tasks/font_install.yml
    - include: tasks/git_repos.yml
    - include: tasks/programs/local.yml
    - include: tasks/greeter.yml
