- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
      changed_when: false
    - name: Remove snapd
      become: true
      apt:
        purge: yes
        name: snapd
    - name: Ensure snaps won't be installed
      become: true
      blockinfile:
        create: yes
        path: /etc/apt/preferences.d/nosnaps.pref
        block:  |
          # To prevent repository packages from triggering the installation of Snap,
          # this file forbids snapd from being installed by APT.
          # For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

          Package: snapd
          Pin: release a=*
          Pin-Priority: -10

  tasks:
    - include: tasks/locale.yml
    - include: tasks/directories.yml
    - include: tasks/font_install.yml
    - include: tasks/git_repos.yml
    - include: tasks/programs/local.yml
