- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update repositories
      become: true
      apt:
        update_cache: yes
        upgrade: 'yes'
      changed_when: false
    - include_tasks: tasks/purge_snapd.yml

  tasks:
    - include_tasks: tasks/directories.yml
    - include_tasks: tasks/git_repos.yml
    - include_tasks: tasks/locale.yml
    - include_tasks: tasks/groups.yml
    - include_tasks: tasks/font_install.yml
    - include_tasks: tasks/programs/local.yml
    - include_tasks: tasks/greeter.yml
    - include_tasks: tasks/plymouth.yml
    # - include_tasks: tasks/pipewire.yml
    - include_tasks: tasks/networking.yml

  post_tasks:
    - name: Update repositories
      become: true
      apt:
        update_cache: yes
        upgrade: 'yes'
      changed_when: false
    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes
