---
- name: Install xorg
  become: true
  community.general.pacman:
    state: present
    name:
      - "xf86-input-libinput"
      - "xf86-input-synaptics"
      - "xf86-video-intel"
      - "xorg-server"
      - "xorg-xinit"
      - "xorg-xinput"
      - "xorg-xrandr"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install xorg
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "xserver-xorg"
      - "xserver-xorg-video-intel"
      - "xf86-input-libinput"
      - "xf86-input-synaptics"
  when: ansible_facts['os_family'] == "Debian"

- name: Check if libinput conf exists
  ansible.builtin.stat:
    path: "/etc/X11/xorg.conf.d/40-libinput.conf"
  register: libinput_conf

- name: Update libinput conf
  become: true
  ansible.builtin.copy:
    src: "files/40-libinput.conf"
    dest: "/etc/X11/xorg.conf.d/40-libinput.conf"
    mode: "644"
  when: not libinput_conf.stat.exists or libinput_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/40-libinput.conf') | checksum }}"

- name: Check if synaptics conf exists
  ansible.builtin.stat:
    path: "/etc/X11/xorg.conf.d/70-synaptics.conf"
  register: synaptics_conf

- name: Update synaptics conf
  become: true
  ansible.builtin.copy:
    src: "files/70-synaptics.conf"
    dest: "/etc/X11/xorg.conf.d/70-synaptics.conf"
    mode: "644"
  when: not synaptics_conf.stat.exists or synaptics_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/70-synaptics.conf') | checksum }}"
