---
- name: Install xorg
  become: true
  vars:
    xorgserver:
      Archlinux: "xorg-server"
      Debian: "xserver-xorg"
    xinit:
      Archlinux: "xorg-xinit"
      Debian: "xinit"
    xinput:
      Archlinux: "xorg-xinput"
      Debian: "xinput"
    xrandr:
      Archlinux: "xorg-xrandr"
      Debian: "xrandr"
    xwayland:
      Archlinux: "xorg-xwayland"
      Debian: "xwayland"
  ansible.builtin.package:
    name:
      - "arandr"
      - "autorandr"
      - "xf86-input-libinput"
      - "xf86-input-synaptics"
      - "{{ xorgserver[ansible_facts['os_family']] }}"
      - "{{ xinit[ansible_facts['os_family']] }}"
      - "{{ xinput[ansible_facts['os_family']] }}"
      - "{{ xrandr[ansible_facts['os_family']] }}"
      - "{{ xwayland[ansible_facts['os_family']] }}"

- name: Check if libinput conf exists
  ansible.builtin.stat:
    path: "/etc/X11/xorg.conf.d/40-libinput.conf"
  register: libinput_conf

- name: Update libinput conf
  become: true
  ansible.builtin.copy:
    src: "files/40-libinput.conf"
    dest: "/etc/X11/xorg.conf.d/40-libinput.conf"
    mode: "644"
  when: not libinput_conf.stat.exists or libinput_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/40-libinput.conf') | checksum }}"

- name: Check if synaptics conf exists
  ansible.builtin.stat:
    path: "/etc/X11/xorg.conf.d/70-synaptics.conf"
  register: synaptics_conf

- name: Update synaptics conf
  become: true
  ansible.builtin.copy:
    src: "files/70-synaptics.conf"
    dest: "/etc/X11/xorg.conf.d/70-synaptics.conf"
    mode: "644"
  when: not synaptics_conf.stat.exists or synaptics_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/70-synaptics.conf') | checksum }}"
