---
- name: Install xorg
  become: true
  pacman:
    state: present
    name:
      - "xf86-input-libinput"
      - "xf86-input-synaptics"
      - "xf86-video-intel"
      - "xorg-server"
      - "xorg-xinit"
      - "xorg-xinput"
      - "xorg-xrandr"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install xorg
  become: true
  apt:
    install_recommends: no
    name:
      - "xserver-xorg"
      - "xserver-xorg-video-intel"
      - "xf86-input-libinput"
      - "xf86-input-synaptics"
  when: ansible_facts['os_family'] == "Debian"

- name: Check if libinput conf exists
  stat:
    path: "/etc/X11/xorg.conf.d/40-libinput.conf"
  register: libinput_conf

- name: Update libinput conf
  become: true
  copy:
    src: "../files/40-libinput.conf"
    dest: "/etc/X11/xorg.conf.d/40-libinput.conf"
  when: libinput_conf.stat.exists == false or libinput_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', '../files/40-libinput.conf') | checksum }}"

- name: Check if synaptics conf exists
  stat:
    path: "/etc/X11/xorg.conf.d/70-synaptics.conf"
  register: synaptics_conf

- name: Update synaptics conf
  become: true
  copy:
    src: "../files/70-synaptics.conf"
    dest: "/etc/X11/xorg.conf.d/70-synaptics.conf"
  when: synaptics_conf.stat.exists == false or synaptics_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', '../files/70-synaptics.conf') | checksum }}"
