---
- name: "Install git and git tools"
  become: true
  ansible.builtin.package:
    name:
      - "act"
      - "difftastic"
      - "git"
      - "git-delta"
      - "lazygit"
      - "mermaid-cli"
