---
- name: Create ssh dir
  file:
    path: "{{ sshkey_dir }}"
    state: directory
    mode: "700"

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ github_key_path }}"
    passphrase: "{{ github_key_passphrase }}"
    type: Ed25519
    size: 2048
    cipher: auto
    mode: "600"

- name: Generate public key
  community.crypto.openssl_publickey:
    path: "{{ github_key_path }}.pub"
    privatekey_path: "{{ github_key_path }}"
    privatekey_passphrase: "{{ github_key_passphrase }}"
    mode: "644"

# https://docs.github.com/en/rest/users/keys?apiVersion=2022-11-28#create-a-public-ssh-key-for-the-authenticated-user
- name: Upload SSH key to GitHub
  ansible.builtin.uri:
    method: POST
    url: "https://api.github.com/user/keys"
    status_code: [201, 304]
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_access_token }}"
      X-GitHub-Api-Version: "2022-11-28"
    body_format: form-urlencoded
    body:
      title: "{{ github_key_title }}"
      key: "{{ lookup('file', github_key_path + '.pub') }}"
  register: github_post

- name: Print upload status
  debug:
    var: github_post.json
