---
- name: "SSH keys"
  ansible.builtin.import_tasks:
    file: "key.yml"

- name: "Git"
  ansible.builtin.import_tasks:
    file: "git.yml"

- name: "GH CLI"
  ansible.builtin.import_tasks:
    file: "gh-cli.yml"
