---
- name: Create ssh dir
  file:
    path: "{{ sshkey_dir }}"
    state: directory
    mode: "700"

- name: Generate private key
  community.crypto.openssh_keypair:
    path: "{{ github_key_path }}"
    passphrase: "{{ github_key_passphrase }}"
    type: "ed25519"
    mode: "600"
  register: private_key

# https://docs.github.com/en/rest/users/keys?apiVersion=2022-11-28#create-a-public-ssh-key-for-the-authenticated-user
- name: Upload SSH key to GitHub
  ansible.builtin.uri:
    method: POST
    url: "https://api.github.com/user/keys"
    status_code: 201
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_access_token }}"
      X-GitHub-Api-Version: "2022-11-28"
    body_format: "json"
    body:
      title: "{{ github_key_title }}"
      key: "{{ lookup('file', github_key_path + '.pub') }}"
  when: private_key.changed or public_key.changed
