---
- name: Create ssh dir
  file:
    path: "{{ sshkey_dir }}"
    state: directory
    mode: "700"

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ github_key_path }}"
    passphrase: "{{ github_key_passphrase }}"
    type: Ed25519
    size: 2048
    cipher: auto
    mode: "600"
  register: private_key

- name: Generate public key
  community.crypto.openssl_publickey:
    path: "{{ github_key_path }}.pub"
    privatekey_path: "{{ github_key_path }}"
    privatekey_passphrase: "{{ github_key_passphrase }}"
    mode: "644"
  register: public_key

- name: Upload SSH key to GitHub
  ansible.builtin.uri:
    url: "https://api.github.com/user/keys"
    method: POST
    body_format: form-urlencoded
    body:
      title: "{{ github_key_title }}"
      key: "{{ lookup('file', github_key_path + '.pub') }}"
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_access_token }}"
    status_code: [201, 304]
  when: private_key.changed or public_key.changed
