---
- name: Create ssh dir
  file:
    path: "{{ sshkey_dir }}"
    state: directory
    mode: "700"

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ github_key_path }}"
    passphrase: "{{ github_key_passphrase }}"
    type: Ed25519
    size: 2048
    cipher: auto
    mode: "600"
  register: private_key

- name: Generate public key
  community.crypto.openssl_publickey:
    path: "{{ github_key_path }}.pub"
    privatekey_path: "{{ github_key_path }}"
    privatekey_passphrase: "{{ github_key_passphrase }}"
    mode: "644"
  register: private_key

- name: Add SSH key to SSH agent
  ansible.builtin.shell:
    cmd: |
      eval "$(ssh-agent)"
      ssh-add {{ github_key_path }}
  when: private_key.changed or public_key.changed

- name: Upload SSH key to GitHub
  ansible.builtin.uri:
    url: "https://api.github.com/user/keys"
    method: POST
    body_format: form-urlencoded
    body:
      title: "{{ github_key_title }}"
      key: "{{ lookup('file', github_key_path + '.pub') }}"
    headers:
      Authorization: "token {{ github_access_token }}"
    status_code: 201
  when: private_key.changed or public_key.changed
  register: github_key

- name: Fail if GitHub key upload fails
  ansible.builtin.fail:
    msg: "Failed to upload SSH key to GitHub"
  when: github_key.status != 201
