# TODO: get the cargo galaxy module to work instead of shell commands
- name: Install rust
  become: true
  apt:
    install_recommends: no
    name: rust-all

- name: Install cargo packages
  # cargo:
  #   name: alacritty
  shell: cargo install alacritty
