---
- name: Install power-profiles-daemon
  become: true
  ansible.builtin.package:
    name:
      - "power-profiles-daemon"

- name: Enable power-profiles-daemon service
  become: true
  ansible.builtin.systemd:
    name: "power-profiles-daemon"
    enabled: true
