---
- name: "Install tlp"
  become: true
  ansible.builtin.package:
    name:
      - "acpid"
      - "throttled"
      - "tlp"

- name: "Check if TLP conf file exists"
  ansible.builtin.stat:
    path: "/etc/tlp.conf"
  register: "tlp_conf"

- name: "Copy TLP conf file"
  become: true
  ansible.builtin.copy:
    src: "files/tlp.conf"
    dest: "/etc/tlp.conf"
    mode: "644"
  when: "not tlp_conf.stat.exists or tlp_conf.stat.checksum != ansible_checksum"
  vars:
    ansible_checksum: "{{ lookup('file', 'files/tlp.conf') | checksum }}"

- name: "Enable tlp service"
  become: true
  ansible.builtin.systemd:
    name: "tlp"
    state: "started"
    enabled: true

- name: "Enable acpid service"
  become: true
  ansible.builtin.systemd:
    name: "acpid"
    state: "started"
    enabled: true

- name: "Start TLP"
  become: true
  ansible.builtin.command: "tlp start"
  changed_when: false
