- name: Create dev directory
  become: true
  become_user: "{{ remote_regular_user }}"
  file:
    path: $HOME/dev
    state: directory

- name: Create documents directory
  become: true
  become_user: "{{ remote_regular_user }}"
  file:
    path: $HOME/documents
    state: directory

- name: Create downloads directory
  become: true
  become_user: "{{ remote_regular_user }}"
  file:
    path: $HOME/downloads
    state: directory

- name: Create pictures directory
  become: true
  become_user: "{{ remote_regular_user }}"
  file:
    path: $HOME/pictures
    state: directory
