- name: Clone dotfiles
  become: true
  become_user: "{{ remote_regular_user }}"
  git:
    repo: https://github.com/KirkEasterson/.dotfiles.git
    dest: $HOME/.dotfiles/

- name: Sym-link dotfiles
  become: true
  become_user: "{{ remote_regular_user }}"
  shell:
    chdir: $HOME/.dotfiles
    cmd: ./install.sh

- name: Clone scripts
  become: true
  become_user: "{{ remote_regular_user }}"
  git:
    repo: https://github.com/KirkEasterson/scripts.git
    dest: $HOME/scripts/
