- name: Clone dotfiles
  become: true
  become_user: "{{ remote_regular_user }}"
  git:
    repo: https://github.com/KirkEasterson/.dotfiles.git
    dest: $HOME/.dotfiles/

- name: Sym-link dotfiles
  become: true
  become_user: "{{ remote_regular_user }}"
  shell:
    chdir: $HOME/.dotfiles
    cmd: ./install.sh

- name: Clone global configs
  become: true
  become_user: "{{ remote_regular_user }}"
  git:
    repo: https://github.com/KirkEasterson/.global_configs.git
    dest: $HOME/.global_configs/

- name: Sym-link global configs
  become: true
  become_user: "{{ remote_regular_user }}"
  script:
    cmd: ~/.global_configs/install.sh

- name: Clone scripts
  become: true
  become_user: "{{ remote_regular_user }}"
  git:
    repo: https://github.com/KirkEasterson/scripts.git
    dest: $HOME/scripts/

- name: Create cache and zsh history directory
  file:
    state: directory
    path: ~/.cache/zsh/

- name: Create zsh history
  file:
    state: touch
    path: ~/.cache/zsh/history
