- name: Install packages for greeter
  become: true
  apt:
    install_recommends: no
    name:
      - slick-greeter
      - lightdm-settings
      - light-locker
      - light-locker-settings
      - xserver-xephyr

- name: Enable lightdm service
  systemd:
    name: lightdm
    enabled: yes
