- name: Install lf
  unarchive:
    remote_src: yes
    src: https://github.com/gokcehan/lf/releases/download/r26/lf-linux-amd64.tar.gz 
    dest: /usr/bin/

- name: Clone lfrun
  git:
    repo: https://github.com/cirala/lfimg.git
    dest: /tmp/lfimg

- name: Build lfrun
  become: true
  become_user: "{{ remote_regular_user }}"
  shell:
    chdir: /tmp/lfimg
    cmd: make install

- name: Get starship prompt install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: a+x

- name: Install starship prompt
  expect:
    chdir: /tmp/
    command: ./starship_install.sh
    responses:
      Install: y

- name: Install whatscli
  unarchive:
    remote_src: yes
    src: https://github.com/normen/whatscli/releases/download/v1.0.11/whatscli-v1.0.11-linux.zip
    dest: /usr/local/bin/

- name: Install discord
  apt:
    deb: https://dl.discordapp.net/apps/linux/0.0.17/discord-0.0.17.deb

- name: Install postman
  unarchive:
    remote_src: yes
    src: https://dl.pstmn.io/download/latest/linux64
    dest: /opt/

- name: Create postman symlink
  file:
    src: /opt/Postman/Postman
    dest: /usr/bin/postman
    state: link
