# https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/

- name: Install pipewire client libraries and wireplumber
  become: true
  apt:
    install_recommends: no
    name:
      - pipewire-audio-client-libraries
      - libspa-0.2-bluetooth
      - libspa-0.2-jack
      - wireplumber

- name: Remove packages
  become: true
  apt:
    name:
      - pipewire-media-session
      - pulseaudio-module-bluetooth

- name: Copy ALSA configuration file
  ansible.builtin.copy:
    src: /usr/share/doc/pipewire/examples/alsa.conf.d/99-pipewire-default.conf
    dest: /etc/alsa/conf.d/

- name: Copy JACK configuration file
  ansible.builtin.copy:
    src: /usr/share/doc/pipewire/examples/ld.so.conf.d/pipewire-jack-*.conf
    dest: /etc/ld.so.conf.d/

- name: Run ldconfig
  become: true
  shell: ldconfig

- name: Enable wireplumber service
  become: yes
  systemd:
    name: wireplumber
    enabled: yes

# - name: Set NetworkManager as the default renderer for netplan
#   become: yes
#   shell: netplan set renderer=NetworkManager
#
# - name: Apply the the new netplan configuration
#   become: yes
#   shell: netplan apply
#
# - name: Disable networkd service
#   become: yes
#   systemd:
#     name: systemd-networkd
#     enabled: no
