# https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/

- name: Install pipewire client libraries and wireplumber
  become: true
  apt:
    install_recommends: no
    name:
      - pipewire-audio-client-libraries
      - libspa-0.2-bluetooth
      - libspa-0.2-jack
      - wireplumber

- name: Remove packages
  become: true
  apt:
    name:
      - pipewire-media-session
      - pulseaudio-module-bluetooth

- name: Copy ALSA configuration file
  become: true
  ansible.builtin.copy:
    src: /usr/share/doc/pipewire/examples/alsa.conf.d/99-pipewire-default.conf
    dest: /etc/alsa/conf.d/99-pipewire-default.conf

- name: Copy JACK configuration files
  copy:
    src: "{{ item }}"
    dest: /usr/share/doc/pipewire/examples/ld.so.conf.d/
  with_fileglob:
    - pipewire-jack-*.conf

- name: Run ldconfig
  become: true
  shell: ldconfig

- name: Enable wireplumber service
  become: yes
  systemd:
    name: wireplumber
    enabled: yes
