tasks:
  - name: Install packages for plymouth
    become: true
    apt:
      install_recommends: no
      name:
        - plymouth
        - plymouth-themes
        - plymouth-x11

  - name: Enable plymouth service
    systemd:
      name: plymouth
      enabled: yes

  - name: Check if 'quiet' is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*quiet'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false

  - name: Insert 'quiet' if missing
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: '\1 quiet"'
    when: grub_cmdline_check.found == 0
    notify: Update grub

  - name: Check if 'splash' is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*splash'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false

  - name: Insert 'splash' if missing
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: '\1 splash"'
    when: grub_cmdline_check.found == 0
    notify: Update grub

  - name: Update initramfs
    become: true
    become_user: "{{ remote_regular_user }}"
    shell:
      cmd: update-initramfs

handlers:
  - name: Update grub
    become: yes
    shell: "update-grub"
