- name: Install flatpak
  become: true
  apt:
    install_recommends: no
    name:
      - flatpak

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  flatpak:
    state: present
    method: user
    name:
      - com.spotify.Client
      - com.google.Chrome
      - org.chromium.Chromium
      - com.discordapp.Discord
      - us.zoom.Zoom
      - com.slack.Slack
      - io.github.mimbrero.WhatsAppDesktop
