---
- name: Setup sddm
  hosts: localhost
  become: true
  when: ansible_system == "Linux"

  tasks:
    - name: Install sddm
      become: true
      pacman:
        state: present
        name:
          - sddm
          - sddm-kcm
      when: ansible_distribution == 'ArchLinux'

    # - name: Install SDDM nordic theme
    #   become: yes
    #   kewlfft.aur.aur:
    #     state: present
    #     use: yay
    #     name:
    #       - sddm-nordic-theme-git

    - name: Check if SDDM conf file exists
      stat:
        path: /etc/sddm.conf
      register: sddm_conf

    - name: Copy default SDDM conf file
      become: true
      copy:
        src: /usr/lib/sddm/sddm.conf.d/default.conf
        dest: /etc/sddm.conf
      when: sddm_conf.stat.exists == false

    - name: Apply SDDM nordic theme
      become: true
      lineinfile:
        path: /etc/sddm.conf
        state: "present"
        regexp: "^Current="
        line: "Current=Nordic-bluish"

    - name: Hide the aur_builder user
      become: true
      lineinfile:
        path: /etc/sddm.conf
        state: "present"
        regexp: "^HideUsers="
        line: "HideUsers=aur_builder"

    - name: Enable sddm service
      become: true
      systemd:
        name: sddm
        enabled: yes
