- name: Install neovim PPA for neovim nightly
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'

- name: Install packages
  become: true
  apt:
    install_recommends: no
    name:
      - git
      - curl
      - tree
      - make
      - cmake
      - gcc
      - build-essential
      - xsel
      - firefox
      - tmux
      - neovim
      - neofetch
      - xclip
      - libxext-dev
      - exiftool
      - libcdio-utils
      - transmission
      - pandoc
      - zathura
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - tlp
      - powertop
      - htop
      - timeshift
      - zsh
      - zsh-common
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - exa
      - bat
      - language-pack-en
      - hwinfo
      - unzip
      - papirus-icon-theme
