- name: Install neovim PPA for neovim nightly
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'

- name: Install volian keyring
  become: true
  apt:
    deb: https://gitlab.com/volian/volian-archive/uploads/b20bd8237a9b20f5a82f461ed0704ad4/volian-archive-keyring_0.1.0_all.deb

- name: Install nala
  become: true
  apt:
    deb: https://gitlab.com/volian/volian-archive/uploads/d6b3a118de5384a0be2462905f7e4301/volian-archive-nala_0.1.0_all.deb

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install apt packages
  become: true
  apt:
    install_recommends: no
    name:
      - bat
      - btop
      - build-essential
      - cmake
      - curl
      - entr
      - exa
      - exiftool
      - firefox
      - fish
      - fonts-font-awesome
      - fonts-noto-color-emoji
      - fzf
      - fzy
      - gcc
      - git
      - gvfs
      - htop
      - hwinfo
      - kitty
      - language-pack-en
      - latexmk
      - libcdio-utils
      - libxext-dev
      - luarocks
      - make
      - mpv
      - nala
      - neofetch
      - neovim
      - pandoc
      - papirus-icon-theme
      - powertop
      - python3-neovim
      - ripgrep
      - steam-devices
      - tex-gyre
      - texlive-fonts-recommended
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - timeshift
      - tlp
      - tmux
      - transmission
      - tree
      - udiskie
      - unzip
      - xclip
      - xsel
      - zathura
      - zsh
      - zsh-common

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes
