- name: Install neovim PPA for neovim nightly
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'

# - name: Add volian scar repo
#   become: true
#   apt_repository:
#     state: present
#     repo: "deb-src https://deb.volian.org/volian/ scar main"
#
- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install apt packages
  become: true
  apt:
    install_recommends: no
    name:
      - bat
      - btop
      - build-essential
      - cmake
      - curl
      - exa
      - exiftool
      - firefox
      - fonts-font-awesome
      - fzf
      - fzy
      - gcc
      - git
      - htop
      - hwinfo
      - kitty
      - language-pack-en
      - libcdio-utils
      - libxext-dev
      - make
      - mpv
      # - nala
      - neofetch
      - neovim
      - pandoc
      - papirus-icon-theme
      - powertop
      - ripgrep
      - steam-devices
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - timeshift
      - tlp
      - tmux
      - transmission
      - tree
      - unzip
      - xclip
      - xsel
      - zathura
      - zsh
      - zsh-common

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes
