# - name: Install regolith PPA for i3-gaps
#   become: true
#   apt_repository:
#     repo: 'ppa:regolith-linux/unstable'

- name: Install packages
  become: true
  apt:
    install_recommends: no
    name:
      - acpi
      - acpi-call-dkms
      - acpid
      - alsa-utils
      - arandr
      - autorandr
      - awesome
      - brightnessctl
      - blueman
      - caffeine
      - cbatticon
      - dmenu
      - dunst
      - feh
      - flameshot
      - fontconfig
      - gparted
      # - i3-gaps
      # - i3lock
      - libnotify-bin
      - librsvg2-common
      - lm-sensors
      - lxappearance
      - mesa-va-drivers
      - mousepad
      - mtpaint
      - network-manager
      - network-manager-gnome
      - pavucontrol
      - pcmanfm
      - playerctl
      - polybar
      - pop-gtk-theme
      - pulseaudio
      - pulseaudio-utils
      - rofi
      - thunar
      - tudu
      - unclutter-xfixes
      - volumeicon-alsa
      - xbacklight
      - xcompmgr
      - xinit
      - xorg
      - xserver-xorg-video-intel
      - xss-lock

- name: Enable autorandr service
  systemd:
    name: autorandr
    enabled: yes

- name: Enable bluetooth service
  systemd:
    name: bluetooth
    enabled: yes
