---
- name: Check if dotfiles exists
  stat:
    path: $HOME/.dotfiles/
  register: dotfiles_dir

- name: Remove old bashrc
  file:
    path: $HOME/.bashrc
    state: absent
  when: dotfiles_dir.stat.exists == false

- name: Remove old bash profile
  file:
    path: $HOME/.bash_profile
    state: absent
  when: dotfiles_dir.stat.exists == false

- name: Remove old bash logout
  file:
    path: $HOME/.bash_logout
    state: absent
  when: dotfiles_dir.stat.exists == false

- name: Clone dotfiles
  git:
    repo: https://github.com/KirkEasterson/.dotfiles.git
    dest: $HOME/.dotfiles/
  when: dotfiles_dir.stat.exists == false

- name: Install dotfiles
  shell:
    cmd: $HOME/.dotfiles/install.sh
  when: dotfiles_dir.stat.exists == false
