---
- name: Check if dotfiles exists
  stat:
    path: $HOME/.dotfiles/
  register: dotfiles_dir

- name: Clone dotfiles
  git:
    repo: https://github.com/KirkEasterson/.dotfiles.git
    dest: $HOME/.dotfiles/
  when: dotfiles_dir.stat.exists == false

- name: Install dotfiles
  shell:
    cmd: $HOME/.dotfiles/install.sh
  when: dotfiles_dir.stat.exists == false
