---
- name: Check if global_configs exists
  stat:
    path: $HOME/.global_configs/
  register: global_configs_dir

- name: Clone global configs
  git:
    repo: "git@github.com:KirkEasterson/.global_configs.git"
    dest: $HOME/.global_configs/
    key_file: "{{ sshkey_path }}"
  when: global_configs_dir.stat.exists == false

- name: Install global configs
  shell:
    chdir: $HOME/.global_configs/
    cmd: ./install.sh
  when: global_configs_dir.stat.exists == false
