---
- name: Install zsh
  ansible.builtin.package:
    name:
      - starship
      - zsh

- name: Change default shell to Zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/bin/zsh"

- name: Create zsh cache
  ansible.builtin.file:
    state: "directory"
    path: "~/.cache/zsh/"
    mode: "755"

- name: Create zsh history
  ansible.builtin.file:
    state: "touch"
    path: "~/.cache/zsh/history"
    mode: "644"
