---
- name: Install zsh from pacman
  become: true
  pacman:
    state: present
    name:
      - starship
      - zsh
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install zsh from apt
  become: true
  apt:
    install_recommends: no
    name:
      - starship
      - zsh
      - zsh-common
  when: ansible_facts['os_family'] == "Debian"

- name: Install zsh from homebrew
  homebrew:
    state: present
    name:
      - starship
      - zsh
  when: ansible_facts['os_family'] == "Darwin"

- name: Change default shell to Zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Create zsh cache
  file:
    state: directory
    path: ~/.cache/zsh/

- name: Check if zsh history exists
  stat:
    path: ~/.cache/zsh/history
  register: zsh_history_file

- name: Create zsh history
  file:
    state: touch
    path: ~/.cache/zsh/history
  when: zsh_history_file.stat.exists == false
