---
- name: "Install zsh"
  become: true
  ansible.builtin.package:
    name:
      - "starship"
      - "wl-clipboard"
      - "xclip"
      - "xsel"
      - "zsh"

- name: "Change default shell to Zsh"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/bin/zsh"

- name: "Create zsh cache"
  ansible.builtin.file:
    state: "directory"
    path: "~/.cache/zsh/"
    mode: "755"

- name: "Check if zsh history exists"
  ansible.builtin.stat:
    path: "~/.cache/zsh/history"
  register: "zsh_history_file"

- name: "Create zsh history"
  ansible.builtin.file:
    state: "touch"
    path: "~/.cache/zsh/history"
    mode: "644"
  when: "not zsh_history_file.stat.exists"
