---
- name: Install zsh from pacman
  become: true
  pacman:
    state: present
    name:
      - starship
      - zsh
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install zsh from apt
  become: true
  apt:
    install_recommends: no
    name:
      - starship
      - zsh
      - zsh-common
  when: ansible_facts['os_family'] == "Debian"

- name: Install zsh from homebrew
  homebrew:
    state: present
    name:
      - starship
      - zsh
  when: ansible_facts['os_family'] == "Darwin"

- name: Check current shell on Linux
  command: "echo $SHELL"
  register: current_shell
  when: "ansible_distribution == 'Linux'"

- name: Check current shell on macOS
  command: "dscl . -read ~/ UserShell | awk '{print $2}'"
  register: current_shell
  when: "ansible_system == 'Darwin'"

- name: Change shell to Zsh
  command: "chsh -s /bin/zsh"
  when: "current_shell.stdout.find('/bin/zsh') == -1"

- name: Create zsh cache
  file:
    state: directory
    path: ~/.cache/zsh/

- name: Check if zsh history exists
  stat:
    path: ~/.cache/zsh/history
  register: zsh_history_file

- name: Create zsh history
  file:
    state: touch
    path: ~/.cache/zsh/history
  when: zsh_history_file.stat.exists == false
