---
- name: Configure networking
  hosts: localhost
  become: true

  tasks:
    - name: Install network-manager on pacman
      become: true
      pacman:
        state: present
        name:
          - modem-manager-gui
          - modemmanager
          - network-manager-applet
          - networkmanager
          - nm-connection-editor
          - usb_modeswitch
      when: ansible_distribution == 'ArchLinux'

    - name: Install network-manager on apt
      become: true
      apt:
        install_recommends: no
        name:
          - network-manager
      when: ansible_os_family == 'Debian'

    - name: Disable networkd service
      become: yes
      systemd:
        name: systemd-networkd
        enabled: no

    - name: Enable network-manager service
      become: yes
      systemd:
        name: NetworkManager
        enabled: yes
        state: started

    - name: Set NetworkManager as the default renderer for netplan
      become: yes
      shell: netplan set renderer=NetworkManager
      when: ansible_distribution == 'Ubuntu'

    - name: Apply the the new netplan configuration
      become: yes
      shell: netplan apply
      when: ansible_distribution == 'Ubuntu'

    - name: Enable mobile-manager service
      become: yes
      systemd:
        name: ModemManager
        enabled: yes
        state: started
