---
- name: "Install DAWs"
  become: true
  ansible.builtin.package:
    name:
      - "ardour"
      - "audacity"
      - "guitarix"
      - "realtime-privileges" # increased memory for ardour
      - "reaper" # not on zypper
      # - "tuxguitar"
