---
- name: Install DAWs
  become: true
  ansible.builtin.package:
    name:
      - "ardour"
      - "guitarix"

- name: Install DAWs from pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - "gxplugins.lv2"
      - "reaper"
