---
- name: DAWs
  ansible.builtin.import_tasks:
    file: daw.yml

- name: Misc
  ansible.builtin.import_tasks:
    file: misc.yml

- name: Pipewire
  ansible.builtin.import_tasks:
    file: pipewire.yml
