---
- name: Install xdg-user-dirs
  become: true
  community.general.pacman:
    state: present
    name:
      - "xdg-user-dirs"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install xdg-user-dirs
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "xdg-user-dirs"
  when: ansible_facts['os_family'] == "Debian"

  # TODO: figure out how to pass the env var, or if it is even necessary
- name: Create xdg user directories
  ansible.builtin.command:
    cmd: "xdg-user-dirs-update --force"
  environment:
    LC_ALL: C
  changed_when: false
  when: ansible_system == "Linux"

- name: Create dev directory
  ansible.builtin.file:
    path: "{{ dev_path }}"
    state: directory
    mode: "755"

- name: Create screenshots directory
  ansible.builtin.file:
    path: "{{ screenshots_path }}"
    state: directory
    mode: "755"
