---
- name: Install xdg-user-dirs
  become: true
  pacman:
    state: present
    name:
      - "xdg-user-dirs"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install xdg-user-dirs
  become: true
  apt:
    install_recommends: no
    name:
      - "xdg-user-dirs"
  when: ansible_facts['os_family'] == "Debian"

- name: Create xdg user directories
  ansible.builtin.shell: "LC_ALL=C xdg-user-dirs-update --force"
  changed_when: false
  when: ansible_system == "Linux"

- name: Create dev directory
  file:
    path: "{{ dev_path }}"
    state: directory

- name: Create screenshots directory
  file:
    path: "{{ screenshots_path }}"
    state: directory
