---
- name: Install browsers
  hosts: localhost
  become: true
  when: (ansible_system == "Linux") or (ansible_distribution == "MacOSX")

  tasks:
    - name: Install browsers from pacman
      become: true
      pacman:
        state: present
        name:
          - chromium
          - firefox
      when: ansible_distribution == 'ArchLinux'

    - name: Install browsers from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        state: present
        use: yay
        name:
          - google-chrome

    - name: Install browsers
      become: true
      apt:
        install_recommends: no
        name:
          - chromium-browser
          - firefox
          # - google-chrome
      when: ansible_os_family == 'Debian'

    - name: Install browsers
      homebrew:
        state: present
        name:
          - chromium
          - firefox
          - google-chrome
      when: ansible_distribution == "MacOSX"
