---
- name: Install docker
  hosts: localhost
  become: true

  tasks:
    - name: Install docker from pacman
      become: true
      pacman:
        state: present
        name:
          - docker
          - docker-buildx
          - docker-compose
          - lazydocker
      when: ansible_distribution == 'ArchLinux'

    - name: Install docker tools from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        state: present
        use: yay
        name:
          - lazydocker

    - name: Install docker from apt
      become: true
      apt:
        install_recommends: no
        name:
          - docker
          - docker-buildx
          - docker-compose
          # - lazydocker
      when: ansible_os_family == 'Debian'

    - name: Install docker from homebrew
      homebrew:
        state: present
        name:
          - docker
          - docker-buildx
          - docker-compose
          - lazydocker
      when: ansible_distribution == "MacOSX"
