---
- name: Install game clients
  hosts: localhost
  become: true

  tasks:
    - name: Install game clients from pacman
      become: true
      pacman:
        state: present
        name:
          - lutris
          - steam
      when: ansible_distribution == 'ArchLinux'

    - name: Install game clients from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        state: present
        use: yay
        name:
          - minecraft-launcher

    - name: Install game clients from apt
      become: true
      apt:
        install_recommends: no
        name:
          - lutris
          - steam
      when: ansible_os_family == 'Debian'

    - name: Install game clients from homebrew
      homebrew:
        state: present
        name:
          - homebrew/cask/minecraft
          - homebrew/cask/steam
      when: ansible_distribution == "MacOSX"
