---
- name: Install launchers
  hosts: localhost
  become: true

  tasks:
    - name: Install launchers from pacman
      become: true
      pacman:
        state: present
        name:
          - rofi
          - wofi
      when: ansible_distribution == 'ArchLinux'

    - name: Install launchers from apt
      become: true
      apt:
        install_recommends: no
        name:
          - rofi
          - wofi
      when: ansible_os_family == 'Debian'

    # # TODO: find a better macos launcher
    # - name: Install launchers from homebrew
    #   homebrew:
    #     state: present
    #     name:
    #       - rofi
    #       - wofi
    #   when: ansible_distribution == "MacOSX"
