---
- name: Install notification services
  hosts: localhost
  become: true
  when: ansible_system == "Linux"

  tasks:
    - name: Install notification services from pacman
      become: true
      pacman:
        state: present
        name:
          - dunst
          - mako
      when: ansible_distribution == 'ArchLinux'

    - name: Install notification services from apt
      become: true
      apt:
        install_recommends: no
        name:
          - dunst
          - mako
      when: ansible_os_family == 'Debian'
