---
- name: "Init"
  ansible.builtin.import_tasks:
    file: "init.yml"

- name: "Refresh package managers"
  ansible.builtin.import_tasks:
    file: "refresh.yml"

- name: "Install AUR"
  ansible.builtin.import_tasks:
    file: "aur.yml"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install homebrew"
  ansible.builtin.import_tasks:
    file: "homebrew.yml"
  when: "ansible_facts['os_family'] == 'Darwin'"

- name: "Install pip"
  ansible.builtin.import_tasks:
    file: "pip.yml"

- name: "Install npm"
  ansible.builtin.import_tasks:
    file: "npm.yml"
