---
- name: Install AUR
  import_tasks:
    file: aur.yml
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install homebrew
  import_tasks:
    file: homebrew.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Install pip
  import_tasks:
    file: pip.yml
