---
- name: Install npm from pacman
  become: true
  pacman:
    state: present
    name:
      - "npm"
      - "nodejs"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install npm from apt
  become: true
  apt:
    install_recommends: no
    name:
      - "npm"
      - "nodejs"
  when: ansible_facts['os_family'] == "Debian"

- name: Install pip from homebrew
  homebrew:
    state: present
    name:
      - "node" # this contains npm and nodejs
  when: ansible_facts['os_family'] == "Darwin"
