---
- name: Install pip from pacman
  become: true
  pacman:
    state: present
    name:
      - "python"
      - "python-pip"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install pip from apt
  become: true
  apt:
    install_recommends: no
    name:
      - "python3" # this might be just `python`
      - "python3-pip"
  when: ansible_facts['os_family'] == "Debian"

- name: Install pip from homebrew
  homebrew:
    state: present
    name:
      - "python"
  when: ansible_facts['os_family'] == "Darwin"
