---
- name: "Install pip from pacman"
  become: true
  community.general.pacman:
    state: "present"
    name:
      - "python"
      - "python-pip"
      - "python-pipx"
  when: "ansible_facts['os_family'] == 'Archlinux'"

- name: "Install pip from apt"
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "python3" # this might be just `python`
      - "python3-pip"
  when: "ansible_facts['os_family'] == 'Debian'"

- name: "Install pip from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "python"
  when: "ansible_facts['os_family'] == 'Darwin'"
