---
- name: Remove lxd snap
  community.general.snap:
    state: absent
    name: lxd

- name: Remove core20 snap
  community.general.snap:
    state: absent
    name: core20

- name: Remove snapd snap
  community.general.snap:
    state: absent
    name: snapd

- name: Disable snapd service
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: snapd.service

- name: Disable snapd socket
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: snapd.socket

- name: Disable snapd seeded service
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: snapd.seeded.service

- name: Remove snapd cache
  become: true
  ansible.builtin.file:
    state: absent
    path: /var/cache/snapd

- name: Purge snapd
  become: true
  ansible.builtin.apt:
    purge: true
    name: snapd

- name: Remove snap directory
  become: true
  ansible.builtin.shell: rm -rf /home/*/snap
  changed_when: false

- name: Ensure snaps won't be installed
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "/etc/apt/preferences.d/nosnaps.pref"
    mode: "644"
    block: |
      # To prevent repository packages from triggering the installation of Snap,
      # this file forbids snapd from being installed by APT.
      # For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

      Package: snapd
      Pin: release a=*
      Pin-Priority: -10

- name: Use firefox deb instead of snap
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "/etc/apt/preferences.d/firefox-no-snap"
    mode: "644"
    block: |
      Package: firefox*
      Pin: release o=Ubuntu*
      Pin-Priority: -1
