---
- name: "Install virtual machine tools"
  become: true
  vars:
    libvirt:
      Archlinux: "libvirt"
      Debian: "libvirt0"
      Suse: "libvirt"
      Darwin: "libvirt"
    qemu:
      Archlinux: "qemu-base"
      Debian: "qemu" # this is wrong
      Suse: "qemu"
      Darwin: "qemu"
  ansible.builtin.package:
    name:
      - "qemu-audio-dbus"
      - "qemu-ui-dbus"
      - "virt-manager"
      - "{{ libvirt[ansible_facts['os_family']] }}"
      - "{{ qemu[ansible_facts['os_family']] }}"

- name: "Add current user to the libvirt group"
  become: true
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    groups: "libvirt"
    append: true

- name: "Enable libvirtd"
  become: true
  ansible.builtin.systemd:
    name: "libvirtd"
    enabled: true
