---
- include_tasks: ../common/tasks/directories/local.yml
- name: Install stow
  become: true
  pacman:
    state: present
    name: stow
- include_tasks: ../common/tasks/git_repos/local.yml
- include_tasks: ../common/tasks/locale.yml
- include_tasks: tasks/programs/local.yml
- include_tasks: ../common/tasks/groups/local.yml

- name: Enable lightdm service
  become: true
  systemd:
    name: lightdm
    enabled: yes

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager
    enabled: yes
