- name: Install volian keyring
  become: true
  apt:
    deb: https://gitlab.com/volian/volian-archive/uploads/b20bd8237a9b20f5a82f461ed0704ad4/volian-archive-keyring_0.1.0_all.deb

- name: Install nala
  become: true
  apt:
    deb: https://gitlab.com/volian/volian-archive/uploads/d6b3a118de5384a0be2462905f7e4301/volian-archive-nala_0.1.0_all.deb

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

