- name: Install neovim PPA for neovim nightly
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
  changed_when: false
