---
- name: Install brightnessctl
  become: true
  pacman:
    state: present
    name:
      - "brightnessctl"
      # - "xorg-xbacklight"
  when: ansible_distribution == 'ArchLinux'

- name: Install brightnessctl
  become: true
  apt:
    install_recommends: no
    name:
      - "brightnessctl"
      # - "xorg-xbacklight"
  when: ansible_os_family == 'Debian'

- name: Check if brightnessctl rules exists
  stat:
    path: "/usr/lib/udev/rules.d/90-brightnessctl.rules"
  register: brightnessctl_conf

- name: Update logind.conf
  copy:
    src: "../files/90-brightnessctl.rules"
    dest: "/usr/lib/udev/rules.d/90-brightnessctl.rules"
  when: brightnessctl_conf.stat.exists == false or brightnessctl_conf.stat.md5 != ansible_checksum.md5
  vars:
    ansible_checksum: "{{ lookup('file', 'files/90-brightnessctl.rules') }}"
