---
- name: Install brightnessctl
  become: true
  pacman:
    state: present
    name:
      - "brightnessctl"
      # - "xorg-xbacklight"
  when: ansible_distribution == 'ArchLinux'

- name: Install brightnessctl
  become: true
  apt:
    install_recommends: no
    name:
      - "brightnessctl"
      # - "xorg-xbacklight"
  when: ansible_os_family == 'Debian'

- name: Copy brightnessctl udev rules
  become: true
  copy:
    src: "../files/90-brightnessctl.rules"
    dest: "/usr/lib/udev/rules.d/90-brightnessctl.rules"
  when: brightnessctl_conf.checksum != ansible_checksum.md5
  vars:
    ansible_checksum: "{{ lookup('file', 'files/90-brightnessctl.rules') }}"
