---
- name: Install brightnessctl
  become: true
  community.general.pacman:
    state: present
    name:
      - "brightnessctl"
      # - "xorg-xbacklight"
  when: ansible_distribution == 'ArchLinux'

- name: Install brightnessctl
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "brightnessctl"
      # - "xorg-xbacklight"
  when: ansible_os_family == 'Debian'

- name: Check if brightnessctl rules exists
  ansible.builtin.stat:
    path: "/usr/lib/udev/rules.d/90-brightnessctl.rules"
  register: brightnessctl_conf

- name: Copy brightnessctl udev rules
  become: true
  ansible.builtin.copy:
    src: "files/90-brightnessctl.rules"
    dest: "/usr/lib/udev/rules.d/90-brightnessctl.rules"
    mode: "644"
  when: not brightnessctl_conf.stat.exists or brightnessctl_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/90-brightnessctl.rules') | checksum }}"
