---
# TODO: get comic code somehow
- name: Configure fonts
  hosts: localhost
  become: true
  when: (ansible_system == "Linux") or (ansible_distribution == "MacOSX")

  tasks:
    - name: Create fonts directory
      become: true
      become_user: "{{ remote_regular_user }}"
      file:
        path: $HOME/.local/share/fonts
        state: directory

    - name: Install fonts on pacman
      become: true
      pacman:
        state: present
        name:
          - font-manager
          - fontconfig
          - noto-fonts
          - noto-fonts-cjk
          - noto-fonts-emoji
          - noto-fonts-extra
          - ttf-hack-nerd
          - ttf-jetbrains-mono-nerd
          - ttf-ubuntu-mono-nerd
          - ttf-ubuntu-nerd
      when: ansible_distribution == 'ArchLinux'

    - name: Install fonts on apt
      become: true
      apt:
        install_recommends: no
        name:
          - fontconfig
          - font-manager
          - fonts-hack-otf
          - fonts-jetbrains-mono
          - fonts-ubuntu
      when: ansible_os_family == 'Debian'

    - name: Install fonts from homebrew
      homebrew:
        state: present
        name:
          - homebrew/cask-fonts/font-hack-nerd-font
          - homebrew/cask-fonts/font-jetbrains-mono-nerd-font
          - homebrew/cask-fonts/font-ubuntu-mono-nerd-font
          - homebrew/cask-fonts/font-ubuntu-nerd-font
      when: ansible_distribution == "MacOSX"
