# - name: Install packages for plymouth
#   become: true
#   apt:
#     install_recommends: no
#     name:
#       - plymouth
#       - plymouth-themes
#       - plymouth-x11

- name: Enable plymouth service
  become: true
  systemd:
    name: plymouth
    enabled: yes

- name: Check if 'quiet' is configured in the boot command
  become: true
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=".*quiet'
    state: absent
  check_mode: true
  register: quiet_param
  changed_when: false

- name: Insert 'quiet' if missing
  become: true
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
    line: '\1 quiet"'
  when: quiet_param.found == false

- name: Check if 'splash' is configured in the boot command
  become: true
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=".*splash'
    state: absent
  check_mode: true
  register: splash_param
  changed_when: false

- name: Insert 'splash' if missing
  become: true
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
    line: '\1 splash"'
  when: splash_param.found == false

- name: Update grub
  become: true
  become_user: root
  shell:
    cmd: update-grub
  when: quiet_param == false or splash_param == false

- name: Update initramfs
  become: true
  become_user: root
  shell:
    cmd: update-initramfs -u
  when: quiet_param == false or splash_param == false
