- name: Install lf[img] dependencies
  become: true
  apt:
    install_recommends: no
    name:
      - ffmpegthumbnailer
      - imagemagick
      - poppler-data
      - poppler-utils
      - epub-utils
      - wkhtmltopdf
      - bat
      - chafa
      - unzip
      - p7zip
      - unrar
      - catdoc
      - docx2txt
      - odt2txt
      - gnumeric
      - libimage-exiftool-perl
      - libcdio-utils
      - transmission
      - mcomix

- name: Install lf
  unarchive:
    remote_src: yes
    src: https://github.com/gokcehan/lf/releases/download/r27/lf-linux-amd64.tar.gz 
    dest: /usr/bin/

- name: Clone lfrun
  git:
    repo: https://github.com/cirala/lfimg.git
    dest: /tmp/lfimg

- name: Build lfrun
  become: true
  become_user: "{{ remote_regular_user }}"
  shell:
    chdir: /tmp/lfimg
    cmd: make install
