---
- name: "Install lightdm"
  become: true
  vars:
    slickgreeter:
      Archlinux: "lightdm-slick-greeter"
      Debian: "slick-greeter"
    xephyr: # TODO: is this necessary?
      Archlinux: "xorg-server-xephyr"
      Debian: "xserver-xephyr"
  ansible.builtin.package:
    name:
      - "light-locker"
      - "lightdm"
      - "{{ slickgreeter[ansible_facts['os_family']] }}"
      - "{{ xephyr[ansible_facts['os_family']] }}"

- name: "Install lightdm stuff on pacman"
  become: true
  community.general.pacman:
    state: "present"
    name:
      - "lightdm-gtk-greeter-settings"
  when: "ansible_distribution == 'ArchLinux'"

- name: "Install lightdm stuff on apt"
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "lightdm-settings"
      - "light-locker-settings"
  when: "ansible_os_family == 'Debian'"

- name: "Create lightdm conf directory"
  become: true
  ansible.builtin.file:
    path: "/etc/lightdm"
    state: "directory"
    mode: "644"

- name: "Check if lightdm.conf exists"
  become: true
  ansible.builtin.stat:
    path: "/etc/lightdm/lightdm.conf"
  register: "lightdm_conf"

- name: "Update lightdm.conf"
  become: true
  ansible.builtin.copy:
    src: "files/lightdm.conf"
    dest: "/etc/lightdm/lightdm.conf"
    mode: "644"
  when: "not lightdm_conf.stat.exists or lightdm_conf.stat.checksum != ansible_checksum"
  vars:
    ansible_checksum: "{{ lookup('file', 'files/lightdm.conf') | checksum }}"

- name: "Check if slick-greeter.conf exists"
  become: true
  ansible.builtin.stat:
    path: "/etc/lightdm/slick-greeter.conf"
  register: "slick_conf"

- name: "Update slick-greeter.conf"
  become: true
  ansible.builtin.copy:
    src: "files/slick-greeter.conf"
    dest: "/etc/lightdm/slick-greeter.conf"
    mode: "644"
  when: "not slick_conf.stat.exists or slick_conf.stat.checksum != ansible_checksum"
  vars:
    ansible_checksum: "{{ lookup('file', 'files/slick-greeter.conf') | checksum }}"

# - name: "Enable lightdm service"
#   become: true
#   ansible.builtin.systemd:
#     name: "lightdm"
#     enabled: true
