---
- name: Install SDDM on pacman
  become: true
  pacman:
    state: present
    name:
      - "sddm"
      - "sddm-kcm"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install SDDM on apt
  become: true
  apt:
    install_recommends: no
    name:
      - "sddm"
      - "sddm-kcm"
  when: ansible_facts['os_family'] == "Debian"

# - name: Install SDDM nordic theme
#   become: yes
#   become_user: aur_builder
#   kewlfft.aur.aur:
#     state: present
#     use: yay
#     name:
#       - sddm-nordic-theme-git

- name: Check if SDDM conf file exists
  stat:
    path: "/etc/sddm.conf"
  register: sddm_conf

- name: Copy SDDM conf file
  become: true
  copy:
    src: "../files/sddm.conf"
    dest: "/etc/sddm.conf"
  when: sddm_conf.stat.exists == false or sddm_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', '../files/sddm.conf') | checksum }}"

- name: Enable sddm service
  become: true
  systemd:
    name: sddm
    enabled: yes
    state: "started"
