---
- name: "Install SDDM"
  become: true
  ansible.builtin.package:
    name:
      - "sddm"

- name: "Check if SDDM conf file exists"
  ansible.builtin.stat:
    path: "/etc/sddm.conf"
  register: "sddm_conf"

- name: "Copy SDDM conf file"
  become: true
  ansible.builtin.copy:
    src: "files/sddm.conf"
    dest: "/etc/sddm.conf"
    mode: "644"
  when: "not sddm_conf.stat.exists or sddm_conf.stat.checksum != ansible_checksum"
  vars:
    ansible_checksum: "{{ lookup('file', 'files/sddm.conf') | checksum }}"

- name: "Enable sddm service"
  become: true
  ansible.builtin.systemd:
    name: "sddm"
    enabled: true
