- name: Get starship prompt install script
  become: true
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: a+x

- name: Install starship prompt
  become: true
  expect:
    chdir: /tmp/
    command: ./starship_install.sh
    responses:
      Install: y
