---

- name: Install dev tools
  become: true
  pacman:
    state: present
    name:
      - "aspnet-runtime"
      - "aspnet-targeting-pack"
      - "base-devel"
      - "clang"
      - "cmake"
      - "code"
      - "composer"
      - "dbeaver"
      - "prettier"
      - "docker"
      - "docker-compose"
      - "dotnet-runtime"
      - "dotnet-sdk"
      - "dotnet-targeting-pack"
      - "dune"
      - "eslint"
      - "eslint_d"
      - "gcc"
      - "ghc"
      - "git"
      - "github-cli"
      - "go"
      - "hyperfine"
      - "jdk-openjdk"
      - "jre-openjdk"
      - "julia"
      - "kotlin"
      - "kubectl"
      - "lazydocker"
      - "lazygit"
      - "lua"
      - "lua_lsluarocks"
      - "make"
      - "minikube"
      - "nodejs"
      - "npm"
      - "ocaml"
      - "opam"
      - "php"
      - "python"
      - "python-pip"
      - "python3"
      - "ruby"
      - "ruby"
      - "rustup"
      - "terraform"
      - "tree-sitter"
      - "tree-sitter-cli"
      - "zig"

- name: Install code editors
  become: true
  pacman:
    state: present
    name:
      - "emacs"
      - "neovide"
      - "neovim"

- name: Install dev AUR tools
  become: true
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - "ghcup-hs-bin"
      - "go-task-bin"
      - "gofumpt"
      - "golangci-lint-bin"
      - "golines"
      - "nvm"
      - "ocaml-ocamlformat"
      - "prettierd"
      - "python-neovim"
      - "ruby-neovim"
      - "tflint"
      - "yamlfmt"
- name: Install terraform autocomplete
  command: terraform -install-autocomplete
  changed_when: false
  failed_when: false
- name: Initialize opam
  command: opam init -a
  changed_when: false
  failed_when: false
