---
- name: Install dev tools
  become: true
  pacman:
    state: present
    name:
      - clang
      - code
      - dbeaver
      - docker
      - docker-compose
      - gcc
      - go
      - jdk-openjdk
      - jre-openjdk
      - kotlin
      - make
      - nodejs
      - npm
      - python3
      - rust
      - rustup
