---
- name: Install dev tools
  become: true
  pacman:
    state: present
    name:
      - aspnet-runtime
      - aspnet-targeting-pack
      - clang
      - code
      - dbeaver
      - docker
      - docker-compose
      - dotnet-runtime
      - dotnet-sdk
      - dotnet-targeting-pack
      - gcc
      - go
      - jdk-openjdk
      - jre-openjdk
      - kotlin
      - kubectl
      - make
      - minikube
      - nodejs
      - npm
      - python3
      - rust
      - terraform

- name: Install terraform autocomplete
  command: terraform -install-autocomplete
  changed_when: false
