---
- name: Install dev tools
  become: true
  pacman:
    state: present
    name:
      - aspnet-runtime
      - aspnet-targeting-pack
      - clang
      - code
      - dbeaver
      - docker
      - docker-compose
      - dotnet-runtime
      - dotnet-sdk
      - dotnet-targeting-pack
      - gcc
      - ghc
      - go
      - jdk-openjdk
      - jre-openjdk
      - kotlin
      - kubectl
      - make
      - minikube
      - nodejs
      - npm
      - ocaml
      - opam
      - python3
      - rustup
      - terraform
      - zig

- name: Install dev AUR tools
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - ghcup-hs-bin
      - nvm

- name: Install terraform autocomplete
  command: terraform -install-autocomplete
  changed_when: false
  failed_when: false
