---
- name: Install dev tools
  become: true
  pacman:
    state: present
    name:
      - "aspnet-runtime"
      - "aspnet-targeting-pack"
      - "clang"
      - "code"
      - "composer"
      - "dbeaver"
      - "docker"
      - "docker-compose"
      - "dotnet-runtime"
      - "dotnet-sdk"
      - "dotnet-targeting-pack"
      - "dune"
      - "eslint"
      - "eslint_d"
      - "gcc"
      - "ghc"
      - "go"
      - "jdk-openjdk"
      - "jre-openjdk"
      - "julia"
      - "kotlin"
      - "kubectl"
      - "lua"
      - "lua_lsluarocks"
      - "make"
      - "minikube"
      - "nodejs"
      - "npm"
      - "ocaml"
      - "opam"
      - "php"
      - "python3"
      - "ruby"
      - "rustup"
      - "terraform"
      - "zig"

- name: Install dev AUR tools
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - "ghcup-hs-bin"
      - "go-task-bin"
      - "golangci-lint-bin"
      - "nvm"

- name: Install terraform autocomplete
  command: terraform -install-autocomplete
  changed_when: false
  failed_when: false

- name: Initialize opam
  command: opam init -a
  changed_when: false
  failed_when: false
