---
- name: Install essential tools
  become: true
  pacman:
    state: present
    name:
      - "acpi"
      - "acpid"
      - "alacritty"
      - "alsa-utils"
      - "arandr"
      - "asciiquarium"
      - "base-devel"
      - "bat"
      - "bluez-utils"
      - "btop"
      - "capitaine-cursors"
      - "cheese"
      - "clang"
      - "cmake"
      - "cmatrix"
      - "cowfortune"
      - "cowsay"
      - "curl"
      - "direnv"
      - "emacs"
      - "espeak-ng"
      - "exa"
      - "eza"
      - "figlet"
      - "font-manager"
      - "fzf"
      - "galculator"
      - "gcc"
      - "git"
      - "github-cli"
      - "grc"
      - "htop"
      - "hyperfine"
      - "kdeconnect"
      - "kitty"
      - "lazygit"
      - "libreoffice"
      - "linux-lts"
      - "linux-lts-headers"
      - "make"
      - "man"
      - "mesa"
      - "mesa-utils"
      - "mpd"
      - "neofetch"
      - "neovide"
      - "neovim"
      - "nmap"
      - "openvpn"
      - "p7zip"
      - "pacman-contrib"
      - "pandoc"
      - "powertop"
      - "python"
      - "python-pip"
      - "ranger"
      - "ripgrep"
      - "rsync"
      - "screenkey"
      - "starship"
      - "steam"
      - "sxhkd"
      - "tar"
      - "texlive"
      - "thunderbird"
      - "tlp"
      - "tmux"
      - "tmuxp"
      - "transmission-cli"
      - "transmission-gtk"
      - "tree"
      - "udiskie"
      - "unrar"
      - "unzip"
      - "vim"
      - "virtualbox"
      - "virtualbox-ext-vnc"
      - "virtualbox-guest-iso"
      - "virtualbox-host-modules-arch"
      - "virtualbox-sdk"
      - "vlc"
      - "wezterm"
      - "wget"
      - "wine"
      - "winetricks"
      - "wireshark-cli"
      - "wireshark-qt"
      - "xcape"
      - "xclip"
      - "xdg-desktop-portal"
      - "xdg-desktop-portal-gtk"
      - "xdg-desktop-portal-xapp"
      - "xdg-user-dirs"
      - "xsel"
      - "youtube-dl"
      - "zellij"
      - "zoxide"
      - "zsh"

- name: Install essential aur tools
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - "1password"
      - "1password-cli"
      - "golangci-lint"
      - "gromit-mpx"
      - "gruvbox-dark-gtk"
      - "minecraft-launcher"
      - "nordvpn-bin" # TODO: run this command `usermod -aG nordvpn $USER`, and start `nordvpnd` service
      - "pamac-all"
      - "postman-bin"
      - "rpi-imager"
      - "slack-desktop"
      - "streamlink-twitch-gui-bin"
      - "tdrop"
      - "timeshift"
      - "ueberzugpp"

- name: Enable tlp service
  become: true
  systemd:
    name: tlp
    enabled: yes
