---
- name: Install essential tools
  become: true
  pacman:
    state: present
    name:
      - base-devel
      - bat
      - btop
      - exa
      - fzf
      - git
      - htop
      - lazygit
      - neovim
      - sxhkd
      - tmux
      - vim
      - zoxide
      - zsh
