---
- name: Install fonts
  become: true
  pacman:
    state: present
    name:
      - fontconfig
      - ttf-ubuntu-font-family
      - ttf-ubuntu-mono-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-ubuntu-nerd
