---
- name: Install hyprland
  become: true
  pacman:
    state: present
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - hyprpaper
      - wofi
      - swayidle

- name: Install hyprland AUR packages
  become: true
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - swaylock-effects
      - waybar-hyprland
      - grimblast-git
      - wdisplays
      - wev
