---
- name: Install networking tools
  become: true
  pacman:
    state: present
    name:
      - networkmanager
      - network-manager-applet

- name: Enable NetworkManager service
  become: yes
  systemd:
    name: NetworkManager
    enabled: yes
