---
- name: Install pipewire
  become: true
  pacman:
    state: present
    name:
      - helvum
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - sof-firmware
      - wireplumber
