---
- name: Install pipewire
  become: true
  pacman:
    state: present
    name:
      - helvum
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - sof-firmware
      - wireplumber

- name: Enable pipwire
  become: true
  become_user: "{{ remote_regular_user }}"
  systemd:
    name: pipewire
    enabled: yes

- name: Enable pipwire-pulse socket
  become: true
  become_user: "{{ remote_regular_user }}"
  systemd:
    name: pipewire-pulse.socket
    enabled: yes

- name: Enable wireplumber service
  become: true
  become_user: "{{ remote_regular_user }}"
  systemd:
    name: wireplumber.service
    enabled: yes
