---
- name: Install QEMU
  become: true
  pacman:
    state: present
    name:
      - qemu-full # TODO: not use full
      - vd-agent
      - virt-manager
      - libguestfs
      - dmg2img

- name: Enable libvirtd service
  become: true
  systemd:
    name: libvirtd
    enabled: yes

- name: Add the current user to libvirt groups
  become: true
  user:
    name: "{{ remote_regular_user }}"
    groups:
      - libvirt
      - libvirt-qemu
      - kvm
      - input
      - disk
    append: yes

# HELPFUL LINKS:
# - general QEMU: https://christitus.com/vm-setup-in-linux/
# - win10 QEMU: https://raphtlw.medium.com/how-to-set-up-a-kvm-qemu-windows-10-vm-ca1789411760
