---
- name: Install theme tools
  become: true
  pacman:
    state: present
    name:
      - lxappearance
      - lxappearance-gtk3
      - papirus-icon-theme
      - picom
      - pop-gtk-theme
      - unclutter
