---
- name: Install x11 packages
  become: true
  pacman:
    state: present
    name:
      - autorandr
      - xf86-video-intel
      - xf86-input-libinput
      - xorg-server
      - xorg-xinit
      - xorg-xinput
      - xorg-xrandr
      - xterm
