---
- name: Install xremap
  become: yes
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - xremap-hypr-bin

- name: Touch the uinput file
  become: true
  file:
    path: /etc/modules-load.d/uinput.conf
    state: touch
    mode: u+rw,g-wx,o-rwx
    modification_time: preserve
    access_time: preserve

- name: Check for uinput module to be loaded
  become: true
  lineinfile:
    state: absent
    path: /etc/modules-load.d/uinput.conf
    regexp: "^uinput$"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Add uinput module to be loaded
  become: true
  lineinfile:
    state: present
    path: /etc/modules-load.d/uinput.conf
    line: uinput
  when: check.found == 0

- name: Apply xremap uinput rules
  become: true
  lineinfile:
    path: /etc/udev/rules.d/99-input.rules
    state: "present"
    create: true
    regexp: "^KERNEL=="
    line: 'KERNEL=="uinput", GROUP="input", MODE="0660"'
