---
- name: "Install plymouth"
  become: true
  ansible.builtin.package:
    name:
      - "plymouth"
      - "plymouth-kcm"

- name: "Check if plymouth conf exists"
  ansible.builtin.stat:
    path: "/etc/plymouth/plymouthd.conf"
  register: "plymouth_conf"

- name: "Update plymouth conf"
  become: true
  ansible.builtin.copy:
    src: "files/plymouthd.conf"
    dest: "/etc/plymouth/plymouthd.conf"
    mode: "644"
  when: "not plymouth_conf.stat.exists or plymouth_conf.stat.checksum != ansible_checksum"
  vars:
    ansible_checksum: "{{ lookup('file', 'files/plymouthd.conf') | checksum }}"

- name: "Check if plymouth hook exists"
  become: true
  ansible.builtin.lineinfile:
    backup: true
    path: "/etc/mkinitcpio.conf"
    regexp: "^HOOKS=\\(.*plymouth"
    state: "absent"
  check_mode: true
  register: "plymouth_hook"
  changed_when: false

- name: "Set plymouth hook if missing"
  become: true
  ansible.builtin.lineinfile:
    backrefs: true
    path: "/etc/mkinitcpio.conf"
    regexp: "^(HOOKS=\\(.*) ([a-z]*crypt[a-z]*.*\\))$"
    line: "\\1 plymouth \\2"
  when: "not plymouth_hook.found"

- name: "Rebuild init"
  become: true
  ansible.builtin.command: "mkinitcpio -p linux-lts"
  changed_when: false
  when: "not plymouth_hook.found"
