---
- name: Install plymouth
  become: true
  pacman:
    state: present
    name:
      - plymouth
  when: ansible_facts['os_family'] == "Archlinux"

  # TODO: not use an AUR theme
- name: Install plymouth theme from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - sematrix-plymouth-theme
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install plymouth
  become: true
  apt:
    install_recommends: no
    name:
      - plymouth
      - plymouth-themes
      - plymouth-x11
  when: ansible_facts['os_family'] == "Debian"

- name: Check if plymouth conf exists
  stat:
    path: "/etc/plymouth/plymouthd.conf"
  register: plymouth_conf

- name: Update plymouth conf
  copy:
    src: files/plymouthd.conf
    dest: "/etc/plymouth/plymouthd.conf"
  when: plymouth_conf.stat.exists == false or plymouth_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/plymouthd.conf') | checksum }}"
