---
- name: "Install plymouth"
  become: true
  ansible.builtin.package:
    name:
      - "plymouth"
      - "plymouth-kcm"

- name: "Check if plymouth conf exists"
  ansible.builtin.stat:
    path: "/etc/plymouth/plymouthd.conf"
  register: "plymouth_conf"

- name: "Update plymouth conf"
  become: true
  ansible.builtin.copy:
    src: "files/plymouthd.conf"
    dest: "/etc/plymouth/plymouthd.conf"
    mode: "644"
  when: "not plymouth_conf.stat.exists or plymouth_conf.stat.checksum != ansible_checksum"
  vars:
    ansible_checksum: "{{ lookup('file', 'files/plymouthd.conf') | checksum }}"

# TODO: enable a service maybe?
