---
- name: Install plymouth
  become: true
  community.general.pacman:
    state: present
    name:
      - plymouth
  when: ansible_facts['os_family'] == "Archlinux"

  # TODO: not use an AUR theme
- name: Install plymouth theme from AUR
  become: true
  kewlfft.aur.aur:
    state: present
    use: yay
    name:
      - sematrix-plymouth-theme
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install plymouth
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - plymouth
      - plymouth-themes
      - plymouth-x11
  when: ansible_facts['os_family'] == "Debian"

- name: Check if plymouth conf exists
  ansible.builtin.stat:
    path: "/etc/plymouth/plymouthd.conf"
  register: plymouth_conf

- name: Update plymouth conf
  become: true
  ansible.builtin.copy:
    src: "files/plymouthd.conf"
    dest: "/etc/plymouth/plymouthd.conf"
    mode: "644"
  when: not plymouth_conf.stat.exists or plymouth_conf.stat.checksum != ansible_checksum
  vars:
    ansible_checksum: "{{ lookup('file', 'files/plymouthd.conf') | checksum }}"

# TODO: enable a service maybe?
