---
- name: "Check if GRUB theme exists"
  become: true
  stat:
    path: "/boot/grub/themes/minegrub/"
  register: "minegrub"

- name: "Install GRUB theme"
  ansible.builtin.import_tasks:
    file: "theme.yml"
  when: "not minegrub.stat.exists"

- name: "Set GRUB theme"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/default/grub"
    regexp: "GRUB_THEME="
    line: "GRUB_THEME=\"/boot/grub/themes/minegrub/theme.txt\""
  register: "grub_theme"

- name: "Set GRUB timeout to 5"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/default/grub"
    regexp: "^GRUB_TIMEOUT="
    line: "GRUB_TIMEOUT=5"
  register: "grub_timeout"

- name: "Check if 'quiet' is configured in the boot command"
  become: true
  ansible.builtin.lineinfile:
    backup: true
    path: "/etc/default/grub"
    regexp: '^GRUB_CMDLINE_LINUX=".*quiet' # yamllint disable-line rule:quoted-strings
    state: "absent"
  check_mode: true
  register: "quiet_param"
  changed_when: false

- name: "Insert 'quiet' if missing"
  become: true
  ansible.builtin.lineinfile:
    backrefs: true
    path: "/etc/default/grub"
    regexp: '^(GRUB_CMDLINE_LINUX=".*)"$' # yamllint disable-line rule:quoted-strings
    line: '\1 quiet"' # yamllint disable-line rule:quoted-strings
  when: "not quiet_param.found"

- name: "Check if 'pstate' is configured in the boot command"
  become: true
  ansible.builtin.lineinfile:
    backup: true
    path: "/etc/default/grub"
    regexp: '^GRUB_CMDLINE_LINUX=".*intel_pstate=disable' # yamllint disable-line rule:quoted-strings
    state: "absent"
  check_mode: true
  register: "pstate_param"
  changed_when: false

- name: "Insert 'pstate' if missing"
  become: true
  ansible.builtin.lineinfile:
    backrefs: true
    path: "/etc/default/grub"
    regexp: '^(GRUB_CMDLINE_LINUX=".*)"$' # yamllint disable-line rule:quoted-strings
    line: '\1 intel_pstate=disable"' # yamllint disable-line rule:quoted-strings
  when: "not pstate_param.found"

- name: "Check if 'splash' is configured in the boot command"
  become: true
  ansible.builtin.lineinfile:
    backup: true
    path: "/etc/default/grub"
    regexp: '^GRUB_CMDLINE_LINUX=".*splash' # yamllint disable-line rule:quoted-strings
    state: "absent"
  check_mode: true
  register: "splash_param"
  changed_when: false

- name: "Insert 'splash' if missing"
  become: true
  ansible.builtin.lineinfile:
    backrefs: true
    path: "/etc/default/grub"
    regexp: '^(GRUB_CMDLINE_LINUX=".*)"$' # yamllint disable-line rule:quoted-strings
    line: '\1 splash"' # yamllint disable-line rule:quoted-strings
  when: "not splash_param.found"

- name: "Update grub"
  become: true
  become_user: "root"
  ansible.builtin.command:
    cmd: "grub-mkconfig -o /boot/grub/grub.cfg"
  when: "ansible_facts['os_family'] != 'Suse' and
    (not grub_theme.changed or
    grub_timeout.changed or
    not quiet_param or
    not splash_param)"
  changed_when: false

- name: "Update grub2"
  become: true
  become_user: "root"
  ansible.builtin.command:
    cmd: "grub2-mkconfig -o /boot/grub/grub.cfg"
  when: "ansible_facts['os_family'] == 'Suse' and
    (not grub_theme.changed or
    grub_timeout.changed or
    not quiet_param or
    not splash_param)"
  changed_when: false
# # TODO: figure out the arch equivalent for this
# - name: Update initramfs
#   become: true
#   become_user: root
#   shell:
#     cmd: update-initramfs -u
#   when: not quiet_param or not splash_param
#   changed_when: false
