---
- name: Create .ssh directory
  ansible.builtin.file:
    path: "~/.ssh"
    mode: "700"
    state: "directory"

- name: Store ansible public key
  copy:
    dest: "{{ sshkey_ansible_path }}.pub"
    mode: "644"
    content: "{{ ansible_key_pulic }}"

- name: Store ansible private key
  copy:
    dest: "{{ sshkey_ansible_path }}"
    mode: "600"
    content: "{{ ansible_key_private }}"

- name: Authorize the ansible key with GitHub
  local_action:
    module: github_key
    name: "ansible"
    token: "{{ github_access_token }}"
    pubkey: "{{ ansible_key_pulic }}"

- name: Add ansible SSH key
  shell: |
    eval "$(ssh-agent)"
    ssh-add {{ sshkey_ansible_path }}
