---
- name: Create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: Generate an SSH keypair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: "ed25519"
    passphrase: "{{ github_ssh_passphrase }}"
    regenerate: "never"
    force: false
  changed_when: false
  register: ssh_key

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: "ansible - {{ remote_regular_user }}"
    token: "{{ github_access_token }}"
    pubkey: "{{ ssh_key.public_key }}"
