---
- name: Create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: Generate an SSH keypair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: "ed25519"
  register: ssh_key

- name: Authorize SSH key with GitHub
  community.general.github_key:
    name: "ansible - {{ ansible - hostname }}"
    token: '{{ github_access_token }}'
    pubkey: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519') }}"
  when: ssh_key.changed
