---
- name: Create .ssh directory
  ansible.builtin.file:
    path: "~/.ssh"
    mode: "700"
    state: "directory"

- name: Generate an SSH keypair for the user
  community.crypto.openssh_keypair:
    path: "{{ sshkey_ansible_path }}"
    type: "{{ sshkey_type }}"
    regenerate: "never"
    force: false
  changed_when: false
  register: sshkey

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: "{{ remote_regular_user }} - {{ ansible_hostname }}"
    token: "{{ github_access_token }}"
    pubkey: "{{ sshkey.public_key }}"
