---
- name: Create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: Generate an SSH keypair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: "ed25519"
  register: ssh_key

- name: Read SSH public key to authorize
  ansible.builtin.shell: cat ~/.ssh/id_ed25519
  register: ssh_pub_key

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: Access Key for Some Machine
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
