name: smoke-test

on: [push]

jobs:

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y stow
      - run: sudo apt-get install -y ansible

      - name: Install requirements
        run: ansible-galaxy install -r requirements.yml

      - name: Run install script
        run: ./install.sh

  test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y stow
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install ansible

      - name: Install requirements
        run: ansible-galaxy install -r requirements.yml

      - name: Run install script
        run: ./install.sh
