---
name: lint

on: [push]

jobs:

  build:

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
      - name: ansible-lint
        uses: ansible/ansible-lint@v24
