---
name: lint

on: [push]

jobs:

  yamllint:

    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3

  ansible-lint:
    if: ${{ false }} # TODO: re-enable after testing is done
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v24
