---
name: "lint"

on: ["push"] # yamllint disable-line rule:truthy

jobs:

  yamllint:

    name: "yamllint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ibiqlik/action-yamllint@v3"

  ansible-lint:
    name: "ansible-lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ansible/ansible-lint@v24"
