---
name: lint

on: [push]

jobs:

  build:

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
      - uses: ansible/ansible-lint@v24
