---
name: "smoke-test"

on: ["push"] # yamllint disable-line rule:truthy

jobs:

  ubuntu:
    if: "${{ false }}" # TODO: re-enable after testing is done
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - run: "sudo apt-get install -y stow ansible"

      - name: "Run playbook"
        uses: "dawidd6/action-ansible-playbook@v2"
        with:
          playbook: "bootstrap.yml"
          vault_password: "${{secrets.VAULT_PASSWORD}}"
          requirements: "requirements.yml"
          options: |
            --verbose

  mac:
    if: "${{ false }}" # TODO: re-enable after testing is done
    runs-on: "macos-latest"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "Homebrew/actions/setup-homebrew@master"
      - run: "brew install stow ansible"

      - name: "Run playbook"
        uses: "dawidd6/action-ansible-playbook@v2"
        with:
          playbook: "bootstrap.yml"
          vault_password: "${{secrets.VAULT_PASSWORD}}"
          requirements: "requirements.yml"
          options: |
            --verbose
