---
- name: Install lockers on pacman
  become: true
  ansible.builtin.package:
    state: present
    name:
      - "i3lock"
      - "swaylock"
      - "xautolock"
      - "xss-lock"
  when: ansible_facts['os_family'] == "Archlinux"
