---
- name: Install lockers on pacman
  become: true
  community.general.pacman:
    state: present
    name:
      - "i3lock"
      - "swaylock"
      - "xautolock"
      - "xss-lock"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install lockers on apt
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - "i3lock"
      - "swaylock"
      - "xautolock"
      - "xss-lock"
  when: ansible_facts['os_family'] == "Debian"
