---
- name: Install lockers on pacman
  become: true
  pacman:
    state: present
    name:
      - "i3lock"
      - "swaylock"
      - "xautolock"
      - "xss-lock"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install lockers on apt
  become: true
  apt:
    install_recommends: no
    name:
      - "i3lock"
      - "swaylock"
      - "xautolock"
      - "xss-lock"
  when: ansible_facts['os_family'] == "Debian"
