---
- name: Check if yay is installed
  command: /bin/bash -c "command -v yay"
  changed_when: false
  failed_when: false
  ignore_errors: true
  register: which_out

- name: Clone yay repo
  become: true
  git:
    repo: https://aur.archlinux.org/yay-git.git
    dest: /opt/yay-git
  when: which_out.rc != 0

- name: Change permission on yay repo
  become: true
  file:
    path: /opt/yay-git
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: true
  when: which_out.rc != 0

- name: Build yay
  command: makepkg -si --noconfirm
  args:
    chdir: /opt/yay-git/
  when: which_out.rc != 0
