---
- name: Check if yay is installed
  command: which yay
  changed_when: false
  failed_when: false
  ignore_errors: true
  register: which_out

- name: Clone yay repo
  git:
    repo: https://aur.archlinux.org/yay-git.git
    dest: /opt/
  when: which_out.rc != 0

- name: Change permission on yay repo
  file:
    path: /opt/yay-git
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: true
  when: which_out.rc != 0

- name: Build yay
  command: makepkg -si
  when: which_out.rc != 0
