---
- name: Install pacaur
  shell: ../../../files/install_pacaur.sh

- name: Install galaxy collections
  shell: ../../../files/install_galaxy_collections.sh

- name: Create the `aur_builder` user
  become: yes
  user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
