---
- name: "Install font config tools"
  become: true
  vars:
    emoji:
      Archlinux: "noto-fonts-emoji"
      Debian: "fonts-noto-color-emoji"
      Suse: "emojione-color-font"
    jetbrainsmono:
      Archlinux: "ttf-jetbrains-mono-nerd"
      Debian: "fonts-jetbrains-mono"
      Suse: "jetbrains-mono-fonts"
    ubuntu:
      Archlinux: "ttf-ubuntu-font-family"
      Debian: "fonts-ubuntu"
      Suse: "ubuntu-fonts"
  ansible.builtin.package:
    name:
      - "font-manager"
      - "fontconfig"
      - "{{ emoji[ansible_facts['os_family']] }}"
      - "{{ jetbrainsmono[ansible_facts['os_family']] }}"
      - "{{ ubuntu[ansible_facts['os_family']] }}"
  when: "ansible_system == 'Linux'"

- name: "Install fonts from homebrew"
  community.general.homebrew:
    state: "present"
    name:
      - "homebrew/cask-fonts/font-hack-nerd-font"
      - "homebrew/cask-fonts/font-jetbrains-mono-nerd-font"
      - "homebrew/cask-fonts/font-ubuntu-mono-nerd-font"
      - "homebrew/cask-fonts/font-ubuntu-nerd-font"
  when: "ansible_distribution == 'MacOSX'"

- name: "Create fonts directory"
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.file:
    path: "$HOME/.local/share/fonts"
    state: "directory"
    mode: "755"

- name: "Copy comic-code"
  ansible.builtin.unarchive:
    src: "files/comic-code.tar.gz"
    dest: "~/.local/share/fonts/"
